// JLPT N2 단어 — { jp, reading, ko, type? }
// type: "i" = い형용사 / "na" = な형용사 / 생략 = 명사·동사·부사(자동 분류)
const N2_WORDS = [

  // ── 명사 (120) ──
  { jp: "不安",       reading: "ふあん",       ko: "불안" },
  { jp: "安心",       reading: "あんしん",     ko: "안심" },
  { jp: "心配",       reading: "しんぱい",     ko: "걱정" },
  { jp: "緊張",       reading: "きんちょう",   ko: "긴장" },
  { jp: "焦り",       reading: "あせり",       ko: "조급함" },
  { jp: "困惑",       reading: "こんわく",     ko: "곤혹" },
  { jp: "戸惑い",     reading: "とまどい",     ko: "당황함" },
  { jp: "落胆",       reading: "らくたん",     ko: "낙담" },
  { jp: "失望",       reading: "しつぼう",     ko: "실망" },
  { jp: "希望",       reading: "きぼう",       ko: "희망" },
  { jp: "願望",       reading: "がんぼう",     ko: "소망" },
  { jp: "欲望",       reading: "よくぼう",     ko: "욕망" },
  { jp: "満足",       reading: "まんぞく",     ko: "만족" },
  { jp: "妥協",       reading: "だきょう",     ko: "타협" },
  { jp: "譲歩",       reading: "じょうほ",     ko: "양보" },
  { jp: "態度",       reading: "たいど",       ko: "태도" },
  { jp: "素振り",     reading: "そぶり",       ko: "기색/태도" },
  { jp: "様子",       reading: "ようす",       ko: "상태/모습" },
  { jp: "表情",       reading: "ひょうじょう", ko: "표정" },
  { jp: "印象",       reading: "いんしょう",   ko: "인상" },
  { jp: "評価",       reading: "ひょうか",     ko: "평가" },
  { jp: "判断",       reading: "はんだん",     ko: "판단" },
  { jp: "決断",       reading: "けつだん",     ko: "결단" },
  { jp: "選択",       reading: "せんたく",     ko: "선택" },
  { jp: "相談",       reading: "そうだん",     ko: "상담/의논" },
  { jp: "検討",       reading: "けんとう",     ko: "검토" },
  { jp: "考慮",       reading: "こうりょ",     ko: "고려" },
  { jp: "配慮",       reading: "はいりょ",     ko: "배려" },
  { jp: "遠慮",       reading: "えんりょ",     ko: "사양" },
  { jp: "慣習",       reading: "かんしゅう",   ko: "관습" },
  { jp: "礼儀",       reading: "れいぎ",       ko: "예의" },
  { jp: "作法",       reading: "さほう",       ko: "예법/방식" },
  { jp: "伝統",       reading: "でんとう",     ko: "전통" },
  { jp: "習慣",       reading: "しゅうかん",   ko: "습관" },
  { jp: "風習",       reading: "ふうしゅう",   ko: "풍습" },
  { jp: "常識",       reading: "じょうしき",   ko: "상식" },
  { jp: "意識",       reading: "いしき",       ko: "의식" },
  { jp: "感覚",       reading: "かんかく",     ko: "감각" },
  { jp: "直感",       reading: "ちょっかん",   ko: "직감" },
  { jp: "第六感",     reading: "だいろっかん", ko: "제6감" },
  { jp: "記憶",       reading: "きおく",       ko: "기억" },
  { jp: "回想",       reading: "かいそう",     ko: "회상" },
  { jp: "追憶",       reading: "ついおく",     ko: "추억" },
  { jp: "想像",       reading: "そうぞう",     ko: "상상" },
  { jp: "幻想",       reading: "げんそう",     ko: "환상" },
  { jp: "妄想",       reading: "もうそう",     ko: "망상" },
  { jp: "予感",       reading: "よかん",       ko: "예감" },
  { jp: "予測",       reading: "よそく",       ko: "예측" },
  { jp: "予想",       reading: "よそう",       ko: "예상" },
  { jp: "推測",       reading: "すいそく",     ko: "추측" },
  { jp: "推奨",       reading: "すいしょう",   ko: "추천/권장" },
  { jp: "動機",       reading: "どうき",       ko: "동기" },
  { jp: "目的",       reading: "もくてき",     ko: "목적" },
  { jp: "目標",       reading: "もくひょう",   ko: "목표" },
  { jp: "志望",       reading: "しぼう",       ko: "지망" },
  { jp: "意欲",       reading: "いよく",       ko: "의욕" },
  { jp: "熱意",       reading: "ねつい",       ko: "열의" },
  { jp: "情熱",       reading: "じょうねつ",   ko: "열정" },
  { jp: "根気",       reading: "こんき",       ko: "끈기" },
  { jp: "忍耐",       reading: "にんたい",     ko: "인내" },
  { jp: "我慢",       reading: "がまん",       ko: "참음" },
  { jp: "努力",       reading: "どりょく",     ko: "노력" },
  { jp: "苦労",       reading: "くろう",       ko: "고생" },
  { jp: "苦痛",       reading: "くつう",       ko: "고통" },
  { jp: "煩悩",       reading: "ぼんのう",     ko: "번뇌" },
  { jp: "憂鬱",       reading: "ゆううつ",     ko: "우울" },
  { jp: "後悔",       reading: "こうかい",     ko: "후회" },
  { jp: "反省",       reading: "はんせい",     ko: "반성" },
  { jp: "自責",       reading: "じせき",       ko: "자책" },
  { jp: "罪悪感",     reading: "ざいあくかん", ko: "죄책감" },
  { jp: "恥",         reading: "はじ",         ko: "부끄러움" },
  { jp: "屈辱",       reading: "くつじょく",   ko: "굴욕" },
  { jp: "羨望",       reading: "せんぼう",     ko: "선망" },
  { jp: "嫉妬",       reading: "しっと",       ko: "질투" },
  { jp: "憎悪",       reading: "ぞうお",       ko: "증오" },
  { jp: "怒り",       reading: "いかり",       ko: "분노" },
  { jp: "憤り",       reading: "いきどおり",   ko: "분개" },
  { jp: "軽蔑",       reading: "けいべつ",     ko: "경멸" },
  { jp: "侮蔑",       reading: "ぶべつ",       ko: "멸시" },
  { jp: "偏見",       reading: "へんけん",     ko: "편견" },
  { jp: "差別",       reading: "さべつ",       ko: "차별" },
  { jp: "優遇",       reading: "ゆうぐう",     ko: "우대" },
  { jp: "待遇",       reading: "たいぐう",     ko: "대우" },
  { jp: "地位",       reading: "ちい",         ko: "지위" },
  { jp: "身分",       reading: "みぶん",       ko: "신분" },
  { jp: "立場",       reading: "たちば",       ko: "입장" },
  { jp: "境遇",       reading: "きょうぐう",   ko: "처지/환경" },
  { jp: "環境",       reading: "かんきょう",   ko: "환경" },
  { jp: "事情",       reading: "じじょう",     ko: "사정" },
  { jp: "背景",       reading: "はいけい",     ko: "배경" },
  { jp: "経緯",       reading: "けいい",       ko: "경위" },
  { jp: "経過",       reading: "けいか",       ko: "경과" },
  { jp: "過程",       reading: "かてい",       ko: "과정" },
  { jp: "段階",       reading: "だんかい",     ko: "단계" },
  { jp: "局面",       reading: "きょくめん",   ko: "국면" },
  { jp: "情勢",       reading: "じょうせい",   ko: "정세" },
  { jp: "傾向",       reading: "けいこう",     ko: "경향" },
  { jp: "流れ",       reading: "ながれ",       ko: "흐름" },
  { jp: "趨勢",       reading: "すうせい",     ko: "추세" },
  { jp: "現状",       reading: "げんじょう",   ko: "현상" },
  { jp: "実態",       reading: "じったい",     ko: "실태" },
  { jp: "実情",       reading: "じつじょう",   ko: "실정" },
  { jp: "本質",       reading: "ほんしつ",     ko: "본질" },
  { jp: "核心",       reading: "かくしん",     ko: "핵심" },
  { jp: "要点",       reading: "ようてん",     ko: "요점" },
  { jp: "重点",       reading: "じゅうてん",   ko: "중점" },
  { jp: "主眼",       reading: "しゅがん",     ko: "주안점" },
  { jp: "着眼",       reading: "ちゃくがん",   ko: "착안" },
  { jp: "視点",       reading: "してん",       ko: "시점/관점" },
  { jp: "視野",       reading: "しや",         ko: "시야" },
  { jp: "展望",       reading: "てんぼう",     ko: "전망" },
  { jp: "構想",       reading: "こうそう",     ko: "구상" },
  { jp: "構図",       reading: "こうず",       ko: "구도" },
  { jp: "枠組み",     reading: "わくぐみ",     ko: "틀/프레임" },
  { jp: "枠",         reading: "わく",         ko: "테두리/한계" },
  { jp: "限界",       reading: "げんかい",     ko: "한계" },
  { jp: "極限",       reading: "きょくげん",   ko: "극한" },
  { jp: "極致",       reading: "きょくち",     ko: "극치" },
  { jp: "頂点",       reading: "ちょうてん",   ko: "정점" },
  { jp: "天辺",       reading: "てっぺん",     ko: "꼭대기" },
  { jp: "底",         reading: "そこ",         ko: "바닥" },
  { jp: "底辺",       reading: "ていへん",     ko: "밑바닥" },
  { jp: "根底",       reading: "こんてい",     ko: "근본" },

  // ── 동사 (90) ──
  { jp: "適する",     reading: "てきする",     ko: "적합하다" },
  { jp: "合う",       reading: "あう",         ko: "맞다/어울리다" },
  { jp: "一致する",   reading: "いっちする",   ko: "일치하다" },
  { jp: "相違する",   reading: "そういする",   ko: "상위(달리)하다" },
  { jp: "異なる",     reading: "ことなる",     ko: "다르다" },
  { jp: "似通う",     reading: "にかよう",     ko: "꼭 닮다" },
  { jp: "近似する",   reading: "きんじする",   ko: "근사하다" },
  { jp: "等しい",     reading: "ひとしい",     ko: "같다", type: "i" },
  { jp: "匹敵する",   reading: "ひってきする", ko: "필적하다" },
  { jp: "凌ぐ",       reading: "しのぐ",       ko: "능가하다/견디다" },
  { jp: "超越する",   reading: "ちょうえつする", ko: "초월하다" },
  { jp: "及ぶ",       reading: "およぶ",       ko: "미치다/이르다" },
  { jp: "及び腰",     reading: "およびごし",   ko: "소극적 태도" },
  { jp: "達する",     reading: "たっする",     ko: "달하다" },
  { jp: "到達する",   reading: "とうたつする", ko: "도달하다" },
  { jp: "到着する",   reading: "とうちゃくする", ko: "도착하다" },
  { jp: "着く",       reading: "つく",         ko: "닿다/도착하다" },
  { jp: "付く",       reading: "つく",         ko: "붙다" },
  { jp: "付き纏う",   reading: "つきまとう",   ko: "뒤따르다" },
  { jp: "纏める",     reading: "まとめる",     ko: "정리하다" },
  { jp: "纏まる",     reading: "まとまる",     ko: "정리되다" },
  { jp: "整える",     reading: "ととのえる",   ko: "정돈하다" },
  { jp: "整う",       reading: "ととのう",     ko: "정돈되다" },
  { jp: "片付ける",   reading: "かたづける",   ko: "정리하다/치우다" },
  { jp: "片付く",     reading: "かたづく",     ko: "정리되다" },
  { jp: "片寄る",     reading: "かたよる",     ko: "치우치다" },
  { jp: "偏る",       reading: "かたよる",     ko: "편중되다" },
  { jp: "均衡する",   reading: "きんこうする", ko: "균형 잡히다" },
  { jp: "平衡を保つ", reading: "へいこうをたもつ", ko: "평형을 유지하다" },
  { jp: "保つ",       reading: "たもつ",       ko: "유지하다" },
  { jp: "維持する",   reading: "いじする",     ko: "유지하다" },
  { jp: "持続する",   reading: "じぞくする",   ko: "지속하다" },
  { jp: "存続する",   reading: "そんぞくする", ko: "존속하다" },
  { jp: "続く",       reading: "つづく",       ko: "이어지다" },
  { jp: "続ける",     reading: "つづける",     ko: "계속하다" },
  { jp: "途切れる",   reading: "とぎれる",     ko: "끊기다" },
  { jp: "絶える",     reading: "たえる",       ko: "끊기다/그치다" },
  { jp: "断つ",       reading: "たつ",         ko: "끊다" },
  { jp: "絶つ",       reading: "たつ",         ko: "끊다/단절하다" },
  { jp: "遮断する",   reading: "しゃだんする", ko: "차단하다" },
  { jp: "断絶する",   reading: "だんぜつする", ko: "단절하다" },
  { jp: "分断する",   reading: "ぶんだんする", ko: "분단하다" },
  { jp: "分裂する",   reading: "ぶんれつする", ko: "분열하다" },
  { jp: "分離する",   reading: "ぶんりする",   ko: "분리하다" },
  { jp: "分解する",   reading: "ぶんかいする", ko: "분해하다" },
  { jp: "分析する",   reading: "ぶんせきする", ko: "분석하다" },
  { jp: "解析する",   reading: "かいせきする", ko: "해석(분석)하다" },
  { jp: "解決する",   reading: "かいけつする", ko: "해결하다" },
  { jp: "解消する",   reading: "かいしょうする", ko: "해소하다" },
  { jp: "解除する",   reading: "かいじょする", ko: "해제하다" },
  { jp: "解放する",   reading: "かいほうする", ko: "해방하다" },
  { jp: "開放する",   reading: "かいほうする", ko: "개방하다" },
  { jp: "公開する",   reading: "こうかいする", ko: "공개하다" },
  { jp: "公表する",   reading: "こうひょうする", ko: "공표하다" },
  { jp: "発表する",   reading: "はっぴょうする", ko: "발표하다" },
  { jp: "表明する",   reading: "ひょうめいする", ko: "표명하다" },
  { jp: "表す",       reading: "あらわす",     ko: "나타내다" },
  { jp: "示す",       reading: "しめす",       ko: "보이다/나타내다" },
  { jp: "現れる",     reading: "あらわれる",   ko: "나타나다" },
  { jp: "浮かぶ",     reading: "うかぶ",       ko: "떠오르다" },
  { jp: "浮かべる",   reading: "うかべる",     ko: "떠올리다/띄우다" },
  { jp: "抱く",       reading: "いだく",       ko: "품다/생각하다" },
  { jp: "抱える",     reading: "かかえる",     ko: "안다/안고 있다" },
  { jp: "負う",       reading: "おう",         ko: "지다/맡다" },
  { jp: "担う",       reading: "になう",       ko: "짊어지다" },
  { jp: "担ぐ",       reading: "かつぐ",       ko: "메다/속다" },
  { jp: "背負う",     reading: "せおう",       ko: "지다/메다" },
  { jp: "支える",     reading: "ささえる",     ko: "지탱하다" },
  { jp: "支払う",     reading: "しはらう",     ko: "지불하다" },
  { jp: "払う",       reading: "はらう",       ko: "내다/털다" },
  { jp: "払い戻す",   reading: "はらいもどす", ko: "환불하다" },
  { jp: "戻す",       reading: "もどす",       ko: "되돌리다" },
  { jp: "戻る",       reading: "もどる",       ko: "돌아가다" },
  { jp: "返す",       reading: "かえす",       ko: "돌려주다" },
  { jp: "返る",       reading: "かえる",       ko: "돌아오다" },
  { jp: "帰着する",   reading: "きちゃくする", ko: "귀착하다" },
  { jp: "結ぶ",       reading: "むすぶ",       ko: "맺다/연결하다" },
  { jp: "結ばれる",   reading: "むすばれる",   ko: "맺어지다" },
  { jp: "連結する",   reading: "れんけつする", ko: "연결하다" },
  { jp: "繋がる",     reading: "つながる",     ko: "연결되다" },
  { jp: "繋ぐ",       reading: "つなぐ",       ko: "잇다" },
  { jp: "関わる",     reading: "かかわる",     ko: "관련되다" },
  { jp: "係わる",   reading: "かかわる",   ko: "관여하다" },                        // かかわり → かかわる
  { jp: "関する",     reading: "かんする",     ko: "관하다" },
  { jp: "及ぼす",     reading: "およぼす",     ko: "미치게 하다" },
  { jp: "影響する",   reading: "えいきょうする", ko: "영향을 주다" },
  { jp: "左右する",   reading: "さゆうする",   ko: "좌우하다" },
  { jp: "支配する",   reading: "しはいする",   ko: "지배하다" },
  { jp: "統治する",   reading: "とうちする",   ko: "통치하다" },
  { jp: "管理する",   reading: "かんりする",   ko: "관리하다" },

  // ── い형용사 (30) ──
  { jp: "等しい",     reading: "ひとしい",     ko: "같다", type: "i" },
  { jp: "近い",       reading: "ちかい",       ko: "가깝다", type: "i" },
  { jp: "遠い",       reading: "とおい",       ko: "멀다", type: "i" },
  { jp: "濃い",       reading: "こい",         ko: "짙다", type: "i" },
  { jp: "薄暗い",     reading: "うすぐらい",   ko: "어둑하다", type: "i" },
  { jp: "暗い",       reading: "くらい",       ko: "어둡다", type: "i" },
  { jp: "明るい",     reading: "あかるい",     ko: "밝다", type: "i" },
  { jp: "鮮やか",     reading: "あざやか",     ko: "선명하다/아름답다", type: "na" },
  { jp: "濃厚",       reading: "のうこう",     ko: "짙고 진하다", type: "na" },
  { jp: "甘い",       reading: "あまい",       ko: "달다/느슨하다", type: "i" },
  { jp: "辛い",       reading: "からい",       ko: "맵다", type: "i" },
  { jp: "辛い",       reading: "つらい",       ko: "괴롭다", type: "i" },
  { jp: "苦い",       reading: "にがい",       ko: "쓰다", type: "i" },
  { jp: "酸っぱい",   reading: "すっぱい",     ko: "시다", type: "i" },
  { jp: "しょっぱい", reading: "しょっぱい",   ko: "짜다", type: "i" },
  { jp: "旨い",       reading: "うまい",       ko: "맛있다/훌륭하다", type: "i" },
  { jp: "まずい",     reading: "まずい",       ko: "맛없다", type: "i" },
  { jp: "賢い",       reading: "かしこい",     ko: "현명하다", type: "i" },
  { jp: "鈍感",       reading: "どんかん",     ko: "둔감하다", type: "na" },
  { jp: "敏感",       reading: "びんかん",     ko: "민감하다", type: "na" },
  { jp: "鋭敏",       reading: "えいびん",     ko: "예민하다", type: "na" },
  { jp: "過敏",       reading: "かびん",       ko: "과민하다", type: "na" },
  { jp: "脆い",       reading: "もろい",       ko: "부서지기 쉽다", type: "i" },
  { jp: "頑丈",       reading: "がんじょう",   ko: "튼튼하다", type: "na" },
  { jp: "堅牢",       reading: "けんろう",     ko: "견고하다", type: "na" },
  { jp: "もろい",     reading: "もろい",       ko: "약하다", type: "i" },
  { jp: "頼もしい",   reading: "たのもしい",   ko: "믿음직하다", type: "i" },
  { jp: "心強い",     reading: "こころづよい", ko: "득득하다", type: "i" },
  { jp: "力強い",     reading: "ちからづよい", ko: "힘이 세다/득득하다", type: "i" },
  { jp: "若々しい",   reading: "わかわかしい", ko: "젊은이 같다", type: "i" },

  // ── な형용사 (30) ──
  { jp: "正確",       reading: "せいかく",     ko: "정확하다", type: "na" },
  { jp: "正確無謬",   reading: "せいかくむびゅう", ko: "정확무류", type: "na" },
  { jp: "精密",       reading: "せいみつ",     ko: "정밀하다", type: "na" },
  { jp: "綿密",       reading: "めんみつ",     ko: "면밀하다", type: "na" },
  { jp: "緻密",       reading: "ちみつ",       ko: "치밀하다", type: "na" },
  { jp: "厳密",       reading: "げんみつ",     ko: "엄밀하다", type: "na" },
  { jp: "慎重",       reading: "しんちょう",   ko: "신중하다", type: "na" },
  { jp: "慎重",       reading: "しんちょう",   ko: "신중하다", type: "na" },
  { jp: "用心",       reading: "ようじん",     ko: "조심함", type: "na" },
  { jp: "油断",       reading: "ゆだん",       ko: "방심", type: "na" },
  { jp: "不注意",     reading: "ふちゅうい",   ko: "부주의", type: "na" },
  { jp: "無謀",       reading: "むぼう",       ko: "무모하다", type: "na" },
  { jp: "大胆",       reading: "だいたん",     ko: "대담하다", type: "na" },
  { jp: "果敢",       reading: "かかん",       ko: "과감하다", type: "na" },
  { jp: "勇敢",       reading: "ゆうかん",     ko: "용감하다", type: "na" },
  { jp: "臆病",       reading: "おくびょう",   ko: "겁이 많다", type: "na" },
  { jp: "小心",       reading: "しょうしん",   ko: "마음이 작다/소심하다", type: "na" },
  { jp: "神経質",     reading: "しんけいしつ", ko: "신경질적이다", type: "na" },
  { jp: "几帳面",     reading: "きちょうめん", ko: "꼼꼼하다", type: "na" },
  { jp: "大雑把",     reading: "おおざっぱ",   ko: "대충대충이다", type: "na" },
  { jp: "大らか",   reading: "おおらか",   ko: "대범하다/여유롭다", type: "na" },  // おおらから → おおらか
  { jp: "のんき",     reading: "のんき",       ko: "태평하다/느긋하다", type: "na" },
  { jp: "呑気",       reading: "のんき",       ko: "태평하다", type: "na" },
  { jp: "楽観的",     reading: "らっかんてき", ko: "낙관적이다", type: "na" },
  { jp: "悲観的",     reading: "ひかんてき",   ko: "비관적이다", type: "na" },
  { jp: "消極的",     reading: "しょうきょくてき", ko: "소극적이다", type: "na" },
  { jp: "能動的",     reading: "のうどうてき", ko: "능동적이다", type: "na" },
  { jp: "受動的",     reading: "じゅどうてき", ko: "수동적이다", type: "na" },
  { jp: "自律的",     reading: "じりつてき",   ko: "자율적이다", type: "na" },
  { jp: "他律的",     reading: "たりつてき",   ko: "타율적이다", type: "na" },

  // ── 부사 (30) ──
  { jp: "しばらく",   ko: "잠시/한동안" },
  { jp: "しばらくの間", ko: "한동" },
  { jp: "一時",       ko: "일시적으로" },
  { jp: "暫く",       ko: "잠시/한동안" },
  { jp: "暫定的",     ko: "잠정적으로" },
  { jp: "当面",       ko: "당분간" },
  { jp: "当分",       ko: "당분간" },
  { jp: "さしあたり", ko: "우선/당장은" },
  { jp: "とりあえず", ko: "우선/일단" },
  { jp: "ひとまず",   ko: "우선/일단" },
  { jp: "いずれ",     ko: "조만간" },
  { jp: "近々",       ko: "근일에" },
   { jp: "近日中",     ko: "근일 내에" },
  { jp: "近いうちに", ko: "가까운 안에" },
  { jp: "早晩",       ko: "조만간" },
  { jp: "遅かれ早かれ", ko: "늦든 빠른 조만간" },   // 이렇게 수정
  { jp: "すんなり",   ko: "순조롭게" },
  { jp: "あっさり",   ko: "담백하게/간단히" },
  { jp: "てっきり",   ko: "분명 ~이라고 생각하다" },
  { jp: "まんまと",   ko: "꼼꼼히 속아서" },
  { jp: "うまく",     ko: "잘/제대로" },
  { jp: "うやむやに", ko: "얼렁뚱땅" },
  { jp: "ぐるぐる",   ko: "빙빙" },
  { jp: "めぐりめぐって", ko: "여러 차례 거쳐" }
];
