// JLPT N5 단어 — { jp, reading, ko, type? }
// type: "i" = い형용사 / "na" = な형용사 / 생략 = 명사·동사·부사(자동 분류)
const N5_WORDS = [

  // ── 명사 (50) ──
  { jp: "水",       reading: "みず",       ko: "물" },
  { jp: "お金",     reading: "おかね",     ko: "돈" },
  { jp: "天気",     reading: "てんき",     ko: "날씨" },
  { jp: "電気",     reading: "でんき",     ko: "전기" },
  { jp: "電車",     reading: "でんしゃ",   ko: "전철" },
  { jp: "自転車",   reading: "じてんしゃ", ko: "자전거" },
  { jp: "飛行機",   reading: "ひこうき",   ko: "비행기" },
  { jp: "病院",     reading: "びょういん", ko: "병원" },
  { jp: "銀行",     reading: "ぎんこう",   ko: "은행" },
  { jp: "郵便局",   reading: "ゆうびんきょく", ko: "우체국" },
  { jp: "図書館",   reading: "としょかん", ko: "도서관" },
  { jp: "教室",     reading: "きょうしつ", ko: "교실" },
  { jp: "会社",     reading: "かいしゃ",   ko: "회사" },
  { jp: "駅前",     reading: "えきまえ",   ko: "역 앞" },
  { jp: "花屋",     reading: "はなや",     ko: "꽃집" },
  { jp: "肉",       reading: "にく",       ko: "고기" },
  { jp: "魚",       reading: "さかな",     ko: "생선" },
  { jp: "野菜",     reading: "やさい",     ko: "야채" },
  { jp: "果物",     reading: "くだもの",   ko: "과일" },
  { jp: "卵",       reading: "たまご",     ko: "계란" },
  { jp: "牛乳",     reading: "ぎゅうにゅう", ko: "우유" },
  { jp: "お茶",     reading: "おちゃ",     ko: "차" },
  { jp: "朝ご飯",   reading: "あさごはん", ko: "아침밥" },
  { jp: "昼ご飯",   reading: "ひるごはん", ko: "점심밥" },
  { jp: "晩ご飯",   reading: "ばんごはん", ko: "저녁밥" },
  { jp: "朝",       reading: "あさ",       ko: "아침" },
  { jp: "昼",       reading: "ひる",       ko: "낮" },
  { jp: "夜",       reading: "よる",       ko: "밤" },
  { jp: "今日",     reading: "きょう",     ko: "오늘" },
  { jp: "明日",     reading: "あした",     ko: "내일" },
  { jp: "昨日",     reading: "きのう",     ko: "어제" },
  { jp: "一週間",   reading: "いっしゅうかん", ko: "일주일" },
  { jp: "誕生日",   reading: "たんじょうび", ko: "생일" },
  { jp: "夏休み",   reading: "なつやすみ", ko: "여름방학" },
  { jp: "休み",     reading: "やすみ",     ko: "휴일/휴가" },
  { jp: "顔",       reading: "かお",       ko: "얼굴" },
  { jp: "目",       reading: "め",         ko: "눈" },
  { jp: "耳",       reading: "みみ",       ko: "귀" },
  { jp: "口",       reading: "くち",       ko: "입" },
  { jp: "手",       reading: "て",         ko: "손" },
  { jp: "足",       reading: "あし",       ko: "다리/발" },
  { jp: "頭",       reading: "あたま",     ko: "머리" },
  { jp: "お腹",     reading: "おなか",     ko: "배" },
  { jp: "机",       reading: "つくえ",     ko: "책상" },
  { jp: "椅子",     reading: "いす",       ko: "의자" },
  { jp: "窓",       reading: "まど",       ko: "창문" },
  { jp: "箱",       reading: "はこ",       ko: "상자" },
  { jp: "景色",     reading: "けしき",     ko: "경치" },
  { jp: "空",       reading: "そら",       ko: "하늘" },
  { jp: "海",       reading: "うみ",       ko: "바다" },

  // ── 동사 (25) ──
  { jp: "会う",     reading: "あう",       ko: "만나다" },
  { jp: "遊ぶ",     reading: "あそぶ",     ko: "놀다" },
  { jp: "歩く",     reading: "あるく",     ko: "걷다" },
  { jp: "言う",     reading: "いう",       ko: "말하다" },
  { jp: "入る",     reading: "はいる",     ko: "들어가다" },
  { jp: "売る",     reading: "うる",       ko: "팔다" },
  { jp: "起きる",   reading: "おきる",     ko: "일어나다" },
  { jp: "泳ぐ",     reading: "およぐ",     ko: "수영하다" },
  { jp: "帰る",     reading: "かえる",     ko: "돌아가다" },
  { jp: "消す",     reading: "けす",       ko: "끄다" },
  { jp: "待つ",     reading: "まつ",       ko: "기다리다" },
  { jp: "立つ",     reading: "たつ",       ko: "서다" },
  { jp: "住む",     reading: "すむ",       ko: "살다" },
  { jp: "死ぬ",     reading: "しぬ",       ko: "죽다" },
  { jp: "知る",     reading: "しる",       ko: "알다" },
  { jp: "寝る",     reading: "ねる",       ko: "자다" },
  { jp: "登る",     reading: "のぼる",     ko: "오르다" },
  { jp: "働く",     reading: "はたらく",   ko: "일하다" },
  { jp: "走る",     reading: "はしる",     ko: "달리다" },
  { jp: "結婚する", reading: "けっこんする", ko: "결혼하다" },
  { jp: "勉強する", reading: "べんきょうする", ko: "공부하다" },
  { jp: "運動する", reading: "うんどうする", ko: "운동하다" },
  { jp: "散歩する", reading: "さんぽする", ko: "산책하다" },
  { jp: "買い物する", reading: "かいものする", ko: "쇼핑하다" },
  { jp: "電話する", reading: "でんわする", ko: "전화하다" },

  // ── い형용사 (12) ──
  { jp: "赤い",     reading: "あかい",     ko: "붉다",     type: "i" },
  { jp: "白い",     reading: "しろい",     ko: "희다",     type: "i" },
  { jp: "黒い",     reading: "くろい",     ko: "검다",     type: "i" },
  { jp: "青い",     reading: "あおい",     ko: "푸르다",   type: "i" },
  { jp: "早い",     reading: "はやい",     ko: "빠르다",   type: "i" },
  { jp: "遅い",     reading: "おそい",     ko: "느리다",   type: "i" },
  { jp: "多い",     reading: "おおい",     ko: "많다",     type: "i" },
  { jp: "少ない",   reading: "すくない",   ko: "적다",     type: "i" },
  { jp: "広い",     reading: "ひろい",     ko: "넓다",     type: "i" },
  { jp: "狭い",     reading: "せまい",     ko: "좁다",     type: "i" },
  { jp: "暑い",     reading: "あつい",     ko: "덥다",     type: "i" },
  { jp: "涼しい",   reading: "すずしい",   ko: "시원하다", type: "i" },

  // ── な형용사 (8) ──
  { jp: "賑やか",   reading: "にぎやか",   ko: "번잡하다/북적이다", type: "na" },
  { jp: "綺麗",     reading: "きれい",     ko: "예쁘다/깨끗하다", type: "na" },
  { jp: "有名",     reading: "ゆうめい",   ko: "유명하다", type: "na" },
  { jp: "暇",       reading: "ひま",       ko: "한가하다", type: "na" },
  { jp: "好き",     reading: "すき",       ko: "좋아하다", type: "na" },
  { jp: "嫌い",     reading: "きらい",     ko: "싫어하다", type: "na" },
  { jp: "色々",     reading: "いろいろ",   ko: "여러 가지", type: "na" },
  { jp: "大丈夫",   reading: "だいじょうぶ", ko: "괜찮다", type: "na" },

  // ── 부사 (15) ──
  { jp: "もう",       ko: "이미" },
  { jp: "まだ",       ko: "아직" },
  { jp: "たぶん",     ko: "아마" },
  { jp: "きっと",     ko: "분명히" },
  { jp: "本当に",     ko: "정말로" },
  { jp: "だんだん",   ko: "점점" },
  { jp: "ゆっくり",   ko: "천천히" },
  { jp: "すぐに",     ko: "곧" },
  { jp: "たくさん",   ko: "많이" },
  { jp: "あまり",     ko: "그다지" },
  { jp: "全然",       ko: "전혀" },
  { jp: "一緒に",     ko: "함께" },
  { jp: "やっと",     ko: "겨우/드디어" },
  { jp: "たまに",     ko: "가끔" },
  { jp: "初めて",     ko: "처음" }
];
