// 일본어 동사 데이터 (JLPT 레벨별 + 어울리는 목적어 태그)
// ※ ko의 첫 번째 뜻이 한국어 문장 번역에 사용됩니다
const VERBS = [

  // ================= N5 =================
  { base: "食べる", masu: "食べます", ko: "먹다", reading: "たべる",
    fits: ["food"] },
  { base: "飲む", masu: "飲みます", ko: "마시다", reading: "のむ",
    fits: ["drink"] },
  { base: "買う", masu: "買います", ko: "사다", reading: "かう",
    fits: ["food", "drink", "goods", "book", "clothes"] },
  { base: "読む", masu: "読みます", ko: "읽다", reading: "よむ",
    fits: ["book", "letter", "news"] },
  { base: "書く", masu: "書きます", ko: "쓰다", reading: "かく",
    fits: ["letter", "word"] },
  { base: "見る", masu: "見ます", ko: "보다", reading: "みる",
    fits: ["movie", "tv", "animal", "photo", "person"] },
  { base: "聞く", masu: "聞きます", ko: "듣다", reading: "きく",
    fits: ["music", "news", "story"] },
  { base: "話す", masu: "話します", ko: "말하다", reading: "はなす",
    fits: ["language", "story"] },
 
// ✅ 수정
{ base: "する", masu: "します", ko: "하다", reading: "する", fits: ["sport", "study", "work", "event", "trip"] },

  { base: "習う", masu: "習います", ko: "배우다", reading: "ならう",
    fits: ["language", "skill"] },
  { base: "教える", masu: "教えます", ko: "가르치다", reading: "おしえる",
    fits: ["language", "skill"] },
  { base: "作る", masu: "作ります", ko: "만들다", reading: "つくる",
    fits: ["food", "goods"] },
  { base: "使う", masu: "使います", ko: "사용하다", reading: "つかう",
    fits: ["goods", "money", "language"] },
  { base: "洗う", masu: "洗います", ko: "씻다", reading: "あらう",
    fits: ["clothes", "dish", "body"] },
  { base: "置く", masu: "置きます", ko: "놓다", reading: "おく",
    fits: ["goods", "bag", "book"] },
  { base: "持つ", masu: "持ちます", ko: "가지다", reading: "もつ",
    fits: ["bag", "umbrella", "goods"] },
  { base: "取る", masu: "取ります", ko: "잡다", reading: "とる",
    fits: ["photo", "note"] },

  // ================= N4 =================
  { base: "忘れる", masu: "忘れます", ko: "잊다", reading: "わすれる",
    fits: ["word", "name", "thing"] },
  { base: "覚える", masu: "覚えます", ko: "외우다", reading: "おぼえる",
    fits: ["word", "language", "name"] },
  { base: "探す", masu: "探します", ko: "찾다", reading: "さがす",
    fits: ["goods", "book", "person", "place", "job"] },
  { base: "貸す", masu: "貸します", ko: "빌려주다", reading: "かす",
    fits: ["money", "book", "goods", "car"] },
  { base: "借りる", masu: "借ります", ko: "빌리다", reading: "かりる",
    fits: ["money", "book", "goods", "car"] },
  { base: "返す", masu: "返します", ko: "돌려주다", reading: "かえす",
    fits: ["money", "book", "goods", "car"] },
  { base: "送る", masu: "送ります", ko: "보내다", reading: "おくる",
    fits: ["letter", "mail", "present"] },
  { base: "払う", masu: "払います", ko: "내다", reading: "はらう",
    fits: ["money", "bill"] },
  { base: "切る", masu: "切ります", ko: "자르다", reading: "きる",
    fits: ["food", "paper"] },
  { base: "開ける", masu: "開けます", ko: "열다", reading: "あける",
    fits: ["window", "door", "box", "can"] },
  { base: "閉める", masu: "閉めます", ko: "닫다", reading: "しめる",
    fits: ["window", "door", "box"] },
  { base: "着る", masu: "着ます", ko: "입다", reading: "きる",
    fits: ["clothes"] },
  { base: "履く", masu: "履きます", ko: "신다", reading: "はく",
    fits: ["shoes"] },
  { base: "乗る", masu: "乗ります", ko: "타다", reading: "のる",
    fits: ["vehicle"] },
  { base: "降りる", masu: "降ります", ko: "내리다", reading: "おりる",
    fits: ["vehicle"] },
  { base: "手伝う", masu: "手伝います", ko: "돕다", reading: "てつだう",
    fits: ["person"] },
  { base: "掃除する", masu: "掃除します", ko: "청소하다", reading: "そうじする",
    fits: ["room", "house"] },
  { base: "洗濯する", masu: "洗濯します", ko: "세탁하다", reading: "せんたくする",
    fits: ["clothes"] },
  { base: "料理する", masu: "料理します", ko: "요리하다", reading: "りょうりする",
    fits: ["food"] },
  { base: "運ぶ", masu: "運びます", ko: "옮기다", reading: "はこぶ",
    fits: ["bag", "box", "furniture"] },
  { base: "直す", masu: "直します", ko: "고치다", reading: "なおす",
    fits: ["goods", "car", "clothes"] },
  { base: "並べる", masu: "並べます", ko: "차리다", reading: "ならべる",
    fits: ["dish", "goods", "book"] },
  { base: "飾る", masu: "飾ります", ko: "장식하다", reading: "かざる",
    fits: ["flower", "goods"] },
  { base: "貯める", masu: "貯めます", ko: "저축하다", reading: "ためる",
    fits: ["money"] },
  { base: "歌う", masu: "歌います", ko: "노래하다", reading: "うたう",
    fits: ["song"] },
  { base: "撮る", masu: "撮ります", ko: "찍다", reading: "とる",
    fits: ["photo", "movie"] },

  // ================= N3 =================
  { base: "選ぶ", masu: "選びます", ko: "고르다", reading: "えらぶ",
    fits: ["goods", "book", "clothes", "food", "job"] },
  { base: "集める", masu: "集めます", ko: "수집하다", reading: "あつめる",
    fits: ["stamp", "coin", "info", "person"] },
  { base: "比べる", masu: "比べます", ko: "비교하다", reading: "くらべる",
    fits: ["goods", "price", "idea"] },
  { base: "調べる", masu: "調べます", ko: "조사하다", reading: "しらべる",
    fits: ["word", "info", "history"] },
  { base: "決める", masu: "決めます", ko: "정하다", reading: "きめる",
    fits: ["date", "plan", "rule"] },
  { base: "続ける", masu: "続けます", ko: "계속하다", reading: "つづける",
    fits: ["activity", "study", "work"] },
  { base: "諦める", masu: "諦めます", ko: "포기하다", reading: "あきらめる",
    fits: ["plan", "dream", "study"] },
  { base: "頼む", masu: "頼みます", ko: "부탁하다", reading: "たのむ",
    fits: ["person", "dish"] },
  { base: "許す", masu: "許します", ko: "용서하다", reading: "ゆるす",
    fits: ["person", "mistake"] },
  { base: "謝る", masu: "謝ります", ko: "사과하다", reading: "あやまる",
    fits: ["person", "mistake"] },
  { base: "褒める", masu: "褒めます", ko: "칭찬하다", reading: "ほめる",
    fits: ["person"] },
  { base: "信じる", masu: "信じます", ko: "믿다", reading: "しんじる",
    fits: ["person", "story", "dream"] },
  { base: "助ける", masu: "助けます", ko: "돕다", reading: "たすける",
    fits: ["person", "animal"] },
  { base: "守る", masu: "守ります", ko: "지키다", reading: "まもる",
    fits: ["rule", "promise", "secret"] },
  { base: "壊す", masu: "壊します", ko: "부수다", reading: "こわす",
    fits: ["goods", "machine"] },
  { base: "片付ける", masu: "片付けます", ko: "정리하다", reading: "かたづける",
    fits: ["room", "desk"] },
  { base: "予約する", masu: "予約します", ko: "예약하다", reading: "よやくする",
    fits: ["restaurant", "hotel", "ticket"] },
  { base: "練習する", masu: "練習します", ko: "연습하다", reading: "れんしゅうする",
    fits: ["sport", "song", "language"] },
  { base: "経験する", masu: "経験します", ko: "경험하다", reading: "けいけんする",
    fits: ["event", "job", "life"] },
  { base: "計画する", masu: "計画します", ko: "계획하다", reading: "けいかくする",
    fits: ["trip", "event", "future"] },
  { base: "準備する", masu: "準備します", ko: "준비하다", reading: "じゅんびする",
    fits: ["food", "party", "exam"] },
  { base: "参加する", masu: "参加します", ko: "참가하다", reading: "さんかする",
    fits: ["event", "meeting", "sport"] },
  { base: "心配する", masu: "心配します", ko: "걱정하다", reading: "しんぱいする",
    fits: ["person", "health", "future"] },
  { base: "安心する", masu: "安心します", ko: "안심하다", reading: "あんしんする",
    fits: ["result", "health"] },
  { base: "成功する", masu: "成功します", ko: "성공하다", reading: "せいこうする",
    fits: ["business", "plan", "exam"] },
  { base: "失敗する", masu: "失敗します", ko: "실패하다", reading: "しっぱいする",
    fits: ["exam", "plan", "cooking"] },
  { base: "翻訳する", masu: "翻訳します", ko: "번역하다", reading: "ほんやくする",
    fits: ["book", "letter", "document"] },
  { base: "説明する", masu: "説明します", ko: "설명하다", reading: "せつめいする",
    fits: ["rule", "plan", "problem"] },
  { base: "注意する", masu: "注意します", ko: "주의하다", reading: "ちゅういする",
    fits: ["health", "mistake", "traffic"] },
  { base: "感動する", masu: "感動します", ko: "감동하다", reading: "かんどうする",
    fits: ["movie", "music", "story"] },

  // ================= N2 =================
  { base: "提案する", masu: "提案します", ko: "제안하다", reading: "ていあんする",
    fits: ["plan", "idea", "project"] },
  { base: "確認する", masu: "確認します", ko: "확인하다", reading: "かくにんする",
    fits: ["mail", "schedule", "info"] },
  { base: "検討する", masu: "検討します", ko: "검토하다", reading: "けんとうする",
    fits: ["plan", "proposal", "problem"] },
  { base: "処理する", masu: "処理します", ko: "처리하다", reading: "しょりする",
    fits: ["paperwork", "problem", "data"] },
  { base: "管理する", masu: "管理します", ko: "관리하다", reading: "かんりする",
    fits: ["health", "time", "money", "team"] },
  { base: "改善する", masu: "改善します", ko: "개선하다", reading: "かいぜんする",
    fits: ["service", "system", "skill"] },
  { base: "解決する", masu: "解決します", ko: "해결하다", reading: "かいけつする",
    fits: ["problem", "trouble"] },
  { base: "実現する", masu: "実現します", ko: "실현하다", reading: "じつげんする",
    fits: ["dream", "plan", "goal"] },
  { base: "維持する", masu: "維持します", ko: "유지하다", reading: "いじする",
    fits: ["health", "quality", "peace"] },
  { base: "獲得する", masu: "獲得します", ko: "획득하다", reading: "かくとくする",
    fits: ["prize", "license", "trust"] },
  { base: "達成する", masu: "達成します", ko: "달성하다", reading: "たっせいする",
    fits: ["goal", "target", "dream"] },
  { base: "発展する", masu: "発展します", ko: "발전하다", reading: "はってんする",
    fits: ["city", "economy", "technology"] },
  { base: "拡大する", masu: "拡大します", ko: "확대하다", reading: "かくだいする",
    fits: ["business", "market", "photo"] },
  { base: "増加する", masu: "増加します", ko: "증가하다", reading: "ぞうかする",
    fits: ["population", "price", "sales"] },
  { base: "減少する", masu: "減少します", ko: "감소하다", reading: "げんしょうする",
    fits: ["population", "price", "sales"] },
  { base: "投資する", masu: "投資します", ko: "투자하다", reading: "とうしする",
    fits: ["money", "stock", "education"] },
  { base: "節約する", masu: "節約します", ko: "절약하다", reading: "せつやくする",
    fits: ["money", "water", "electricity"] },
  { base: "保護する", masu: "保護します", ko: "보호하다", reading: "ほごする",
    fits: ["environment", "animal", "child"] },
  { base: "開発する", masu: "開発します", ko: "개발하다", reading: "かいはつする",
    fits: ["product", "software", "land"] },
  { base: "設計する", masu: "設計します", ko: "설계하다", reading: "せっけいする",
    fits: ["building", "software", "machine"] },
  { base: "建設する", masu: "建設します", ko: "건설하다", reading: "けんせつする",
    fits: ["building", "road", "bridge"] },
  { base: "製造する", masu: "製造します", ko: "제조하다", reading: "せいぞうする",
    fits: ["product", "car", "machine"] },
  { base: "出版する", masu: "出版します", ko: "출판하다", reading: "しゅっぱんする",
    fits: ["book", "magazine"] },
  { base: "放送する", masu: "放送します", ko: "방송하다", reading: "ほうそうする",
    fits: ["program", "news", "music"] },
  { base: "宣伝する", masu: "宣伝します", ko: "선전하다", reading: "せんでんする",
    fits: ["product", "event", "shop"] },
  { base: "輸出する", masu: "輸出します", ko: "수출하다", reading: "ゆしゅつする",
    fits: ["product", "car", "food"] },
  { base: "輸入する", masu: "輸入します", ko: "수입하다", reading: "ゆにゅうする",
    fits: ["product", "car", "food"] },
  { base: "迎える", masu: "迎えます", ko: "마중 나가다", reading: "むかえる",
    fits: ["guest", "newyear", "birthday"] },
  { base: "我慢する", masu: "我慢します", ko: "참다", reading: "がまんする",
    fits: ["pain", "desire", "anger"] },

  // ================= N1 =================
  { base: "遂行する", masu: "遂行します", ko: "수행하다", reading: "しゅこうする",
    fits: ["duty", "mission", "task"] },
  { base: "履行する", masu: "履行します", ko: "이행하다", reading: "りこうする",
    fits: ["contract", "promise", "duty"] },
  { base: "統括する", masu: "統括します", ko: "총괄하다", reading: "とうかつする",
    fits: ["project", "team", "branch"] },
  { base: "吟味する", masu: "吟味します", ko: "엄선하다", reading: "ぎんみする",
    fits: ["material", "candidate", "word"] },
  { base: "推進する", masu: "推進します", ko: "추진하다", reading: "すいしんする",
    fits: ["policy", "project", "reform"] },
  { base: "促進する", masu: "促進します", ko: "촉진하다", reading: "そくしんする",
    fits: ["growth", "trade", "development"] },
  { base: "抑制する", masu: "抑制します", ko: "억제하다", reading: "よくせいする",
    fits: ["emotion", "inflation", "impulse"] },
  { base: "締結する", masu: "締結します", ko: "체결하다", reading: "ていけつする",
    fits: ["contract", "treaty", "agreement"] },
  { base: "賠償する", masu: "賠償します", ko: "배상하다", reading: "ばいしょうする",
    fits: ["damage", "loss"] },
  { base: "免除する", masu: "免除します", ko: "면제하다", reading: "めんじょする",
    fits: ["tax", "fee", "duty"] },
  { base: "撤回する", masu: "撤回します", ko: "철회하다", reading: "てっかいする",
    fits: ["statement", "plan", "opinion"] },
  { base: "廃止する", masu: "廃止します", ko: "폐지하다", reading: "はいしする",
    fits: ["system", "rule", "custom"] },
  { base: "制定する", masu: "制定します", ko: "제정하다", reading: "せいていする",
    fits: ["law", "rule", "policy"] },
  { base: "施行する", masu: "施行します", ko: "시행하다", reading: "しこうする",
    fits: ["law", "policy", "system"] },
  { base: "遵守する", masu: "遵守します", ko: "준수하다", reading: "じゅんしゅする",
    fits: ["law", "rule", "deadline"] },
  { base: "違反する", masu: "違反します", ko: "위반하다", reading: "いはんする",
    fits: ["law", "rule", "traffic"] },
  { base: "侵害する", masu: "侵害します", ko: "침해하다", reading: "しんがいする",
    fits: ["rights", "privacy", "copyright"] },
  { base: "干渉する", masu: "干渉します", ko: "간섭하다", reading: "かんしょうする",
    fits: ["affairs", "politics", "privacy"] },
  { base: "妥協する", masu: "妥協します", ko: "타협하다", reading: "だきょうする",
    fits: ["condition", "price", "opinion"] },
  { base: "譲歩する", masu: "譲歩します", ko: "양보하다", reading: "じょうほする",
    fits: ["position", "demand", "opinion"] },
  { base: "克服する", masu: "克服します", ko: "극복하다", reading: "こくふくする",
    fits: ["difficulty", "crisis", "weakness"] },
  { base: "挫折する", masu: "挫折します", ko: "좌절하다", reading: "ざせつする",
    fits: ["dream", "plan", "career"] },
  { base: "奮闘する", masu: "奮闘します", ko: "분투하다", reading: "ふんとうする",
    fits: ["work", "project", "game"] },
  { base: "精進する", masu: "精進します", ko: "정진하다", reading: "しょうじんする",
    fits: ["study", "art", "craft"] },
  { base: "研鑽する", masu: "研鑽します", ko: "연마하다", reading: "けんさんする",
    fits: ["skill", "knowledge", "technique"] }
];
// 부사 데이터
// type: "adjMod" = 형용사 꾸밈 | "verbPre" = 동사 앞
const ADVERBS = [
  // 형용사를 꾸미는 부사
  { jp: "とても",   reading: "とても",   ko: "매우",   type: "adjMod" },
  { jp: "すこし",   reading: "すこし",   ko: "조금",   type: "adjMod" },
  { jp: "いちばん", reading: "いちばん", ko: "가장",   type: "adjMod" },
  { jp: "ちょっと", reading: "ちょっと", ko: "좀",     type: "adjMod" },

  // 동사를 꾸미는 부사
  { jp: "よく",     reading: "よく",     ko: "자주",   type: "verbPre" },
  { jp: "いつも",   reading: "いつも",   ko: "항상",   type: "verbPre" },
  { jp: "ときどき", reading: "ときどき", ko: "때때로", type: "verbPre" },
  { jp: "ゆっくり", reading: "ゆっくり", ko: "천천히", type: "verbPre" },
  { jp: "はやく",   reading: "はやく",   ko: "빨리",   type: "verbPre" }
];
