// 목적어 데이터 (tag = 동사의 fits와 연결)
const OBJECTS = [
  // 음식 food
  { jp: "パン",     reading: "ぱん",       ko: "빵",           tag: "food" },
  { jp: "肉",       reading: "にく",       ko: "고기",         tag: "food" },
  { jp: "魚",       reading: "さかな",     ko: "생선",         tag: "food" },
  { jp: "野菜",     reading: "やさい",     ko: "야채",         tag: "food" },
  { jp: "果物",     reading: "くだもの",   ko: "과일",         tag: "food" },
  { jp: "卵",       reading: "たまご",     ko: "계란",         tag: "food" },
  { jp: "ケーキ",   reading: "けーき",     ko: "케이크",       tag: "food" },
  { jp: "寿司",     reading: "すし",       ko: "스시",         tag: "food" },

  // 음료 drink
  { jp: "水",       reading: "みず",       ko: "물",           tag: "drink" },
  { jp: "お茶",     reading: "おちゃ",     ko: "차",           tag: "drink" },
  { jp: "コーヒー", reading: "こーひー",   ko: "커피",         tag: "drink" },
  { jp: "ジュース", reading: "じゅーす",   ko: "주스",         tag: "drink" },
  { jp: "牛乳",     reading: "ぎゅうにゅう", ko: "우유",       tag: "drink" },
  { jp: "ビール",   reading: "びーる",     ko: "맥주",         tag: "drink" },

  // 물건 goods
  { jp: "時計",     reading: "とけい",     ko: "시계",         tag: "goods" },
  { jp: "傘",       reading: "かさ",       ko: "우산",         tag: "goods" },
  { jp: "鍵",       reading: "かぎ",       ko: "열쇠",         tag: "goods" },
  { jp: "カメラ",   reading: "かめら",     ko: "카메라",       tag: "goods" },
  { jp: "パソコン", reading: "ぱそこん",   ko: "컴퓨터",       tag: "goods" },
  { jp: "携帯電話", reading: "けいたいでんわ", ko: "휴대폰",   tag: "goods" },
  { jp: "家具",     reading: "かぐ",       ko: "가구",         tag: "furniture" },

  // 가방/소지품 bag
  { jp: "かばん",   reading: "かばん",     ko: "가방",         tag: "bag" },
  { jp: "財布",     reading: "さいふ",     ko: "지갑",         tag: "bag" },

  // 옷 clothes / 신발 shoes
  { jp: "服",       reading: "ふく",       ko: "옷",           tag: "clothes" },
  { jp: "靴",       reading: "くつ",       ko: "신발",         tag: "shoes" },
  { jp: "帽子",     reading: "ぼうし",     ko: "모자",         tag: "clothes" },

  // 책 book / 편지 letter / 서류 document
  { jp: "本",       reading: "ほん",       ko: "책",           tag: "book" },
  { jp: "雑誌",     reading: "ざっし",     ko: "잡지",         tag: "book" },
  { jp: "新聞",     reading: "しんぶん",   ko: "신문",         tag: "news" },
  { jp: "手紙",     reading: "てがみ",     ko: "편지",         tag: "letter" },
  { jp: "メール",   reading: "めーる",     ko: "이메일",       tag: "mail" },
  { jp: "書類",     reading: "しょるい",   ko: "서류",         tag: "document" },

  // 말/언어 language, word, story
  { jp: "日本語",   reading: "にほんご",   ko: "일본어",       tag: "language" },
  { jp: "英語",     reading: "えいご",     ko: "영어",         tag: "language" },
  { jp: "単語",     reading: "たんご",     ko: "단어",         tag: "word" },
  { jp: "話",       reading: "はなし",     ko: "이야기",       tag: "story" },
  { jp: "嘘",       reading: "うそ",       ko: "거짓말",       tag: "story" },

  // 돈 money / 요금 bill
  { jp: "お金",     reading: "おかね",     ko: "돈",           tag: "money" },
  { jp: "給料",     reading: "きゅうりょう", ko: "월급",       tag: "money" },
  { jp: "請求書",   reading: "せいきゅうしょ", ko: "청구서",   tag: "bill" },

  // 미디어 movie, music, photo, tv
  { jp: "映画",     reading: "えいが",     ko: "영화",         tag: "movie" },
  { jp: "音楽",     reading: "おんがく",   ko: "음악",         tag: "music" },
  { jp: "歌",       reading: "うた",       ko: "노래",         tag: "song" },
  { jp: "写真",     reading: "しゃしん",   ko: "사진",         tag: "photo" },
  { jp: "テレビ",   reading: "てれび",     ko: "텔레비전",     tag: "tv" },

  // 사람 person
  { jp: "友達",     reading: "ともだち",   ko: "친구",         tag: "person" },
  { jp: "家族",     reading: "かぞく",     ko: "가족",         tag: "person" },
  { jp: "先生",     reading: "せんせい",   ko: "선생님",       tag: "person" },
  { jp: "子供",     reading: "こども",     ko: "아이",         tag: "person" },

  // 동물 animal
  { jp: "犬",       reading: "いぬ",       ko: "개",           tag: "animal" },
  { jp: "猫",       reading: "ねこ",       ko: "고양이",       tag: "animal" },
  { jp: "鳥",       reading: "とり",       ko: "새",           tag: "animal" },

  // 장소 place / 방 room
  { jp: "駅",       reading: "えき",       ko: "역",           tag: "place" },
  { jp: "公園",     reading: "こうえん",   ko: "공원",         tag: "place" },
  { jp: "部屋",     reading: "へや",       ko: "방",           tag: "room" },
  { jp: "家",       reading: "いえ",       ko: "집",           tag: "house" },

  // 창문/문 window, door
  { jp: "窓",       reading: "まど",       ko: "창문",         tag: "window" },
  { jp: "ドア",     reading: "どあ",       ko: "문",           tag: "door" },

  // 교통 vehicle
  { jp: "バス",     reading: "ばす",       ko: "버스",         tag: "vehicle" },
  { jp: "電車",     reading: "でんしゃ",   ko: "전차",         tag: "vehicle" },
  { jp: "車",       reading: "くるま",     ko: "자동차",       tag: "vehicle" },

  // 활동 activity / 공부 study / 일 work
  { jp: "スポーツ", reading: "すぽーつ",   ko: "스포츠",       tag: "sport" },
  { jp: "宿題",     reading: "しゅくだい", ko: "숙제",         tag: "study" },
  { jp: "仕事",     reading: "しごと",     ko: "일",           tag: "work" },

   // 기타 추상 개념 (계속)
  { jp: "目標",     reading: "もくひょう", ko: "목표",         tag: "goal" },
  { jp: "規則",     reading: "きそく",     ko: "규칙",         tag: "rule" },
  { jp: "秘密",     reading: "ひみつ",     ko: "비밀",         tag: "secret" },
  { jp: "約束",     reading: "やくそく",   ko: "약속",         tag: "promise" },
  { jp: "契約",     reading: "けいやく",   ko: "계약",         tag: "contract" },
  { jp: "法律",     reading: "ほうりつ",   ko: "법률",         tag: "law" },
  { jp: "権利",     reading: "けんり",     ko: "권리",         tag: "rights" },
  { jp: "プライバシー", reading: "ぷらいばしー", ko: "프라이버시", tag: "privacy" },
  { jp: "環境",     reading: "かんきょう", ko: "환경",         tag: "environment" },
  { jp: "経済",     reading: "けいざい",   ko: "경제",         tag: "economy" },
  { jp: "技術",     reading: "ぎじゅつ",   ko: "기술",         tag: "technology" },
  { jp: "製品",     reading: "せいひん",   ko: "제품",         tag: "product" },
  { jp: "市場",     reading: "しじょう",   ko: "시장",         tag: "market" },
  { jp: "人口",     reading: "じんこう",   ko: "인구",         tag: "population" },
  { jp: "物価",     reading: "ぶっか",     ko: "물가",         tag: "price" },
  { jp: "売上",     reading: "うりあげ",   ko: "매출",         tag: "sales" },
  { jp: "株",       reading: "かぶ",       ko: "주식",         tag: "stock" },
  { jp: "電気",     reading: "でんき",     ko: "전기",         tag: "electricity" },
  { jp: "水道",     reading: "すいどう",   ko: "수도",         tag: "water" },
  { jp: "痛み",     reading: "いたみ",     ko: "통증",         tag: "pain" },
  { jp: "感情",     reading: "かんじょう", ko: "감정",         tag: "emotion" },
  { jp: "怒り",     reading: "いかり",     ko: "분노",         tag: "anger" },
  { jp: "欲求",     reading: "よっきゅう", ko: "욕구",         tag: "desire" },
  { jp: "衝動",     reading: "しょうどう", ko: "충동",         tag: "impulse" },
  { jp: "インフレ", reading: "いんふれ",   ko: "인플레",       tag: "inflation" },
  { jp: "成長",     reading: "せいちょう", ko: "성장",         tag: "growth" },
  { jp: "発展",     reading: "はってん",   ko: "발전",         tag: "development" },
  { jp: "貿易",     reading: "ぼうえき",   ko: "무역",         tag: "trade" },
  { jp: "改革",     reading: "かいかく",   ko: "개혁",         tag: "reform" },
  { jp: "政策",     reading: "せいさく",   ko: "정책",         tag: "policy" },
  { jp: "条約",     reading: "じょうやく", ko: "조약",         tag: "treaty" },
  { jp: "協定",     reading: "きょうてい", ko: "협정",         tag: "agreement" },
  { jp: "損害",     reading: "そんがい",   ko: "손해",         tag: "damage" },
  { jp: "税金",     reading: "ぜいきん",   ko: "세금",         tag: "tax" },
  { jp: "料金",     reading: "りょうきん", ko: "요금",         tag: "fee" },
  { jp: "義務",     reading: "ぎむ",       ko: "의무",         tag: "duty" },
  { jp: "任務",     reading: "にんむ",     ko: "임무",         tag: "mission" },
  { jp: "課題",     reading: "かだい",     ko: "과제",         tag: "task" },
  { jp: "声明",     reading: "せいめい",   ko: "성명",         tag: "statement" },
  { jp: "意見",     reading: "いけん",     ko: "의견",         tag: "opinion" },
  { jp: "要求",     reading: "ようきゅう", ko: "요구",         tag: "demand" },
  { jp: "立場",     reading: "たちば",     ko: "입장",         tag: "position" },
  { jp: "制度",     reading: "せいど",     ko: "제도",         tag: "system" },
  { jp: "習慣",     reading: "しゅうかん", ko: "습관",         tag: "custom" },
  { jp: "期限",     reading: "きげん",     ko: "기한",         tag: "deadline" },
  { jp: "交通",     reading: "こうつう",   ko: "교통",         tag: "traffic" },
  { jp: "著作権",   reading: "ちょさくけん", ko: "저작권",     tag: "copyright" },
  { jp: "政治",     reading: "せいじ",     ko: "정치",         tag: "politics" },
  { jp: "内政",     reading: "ないせい",   ko: "내정",         tag: "affairs" },
  { jp: "条件",     reading: "じょうけん", ko: "조건",         tag: "condition" },
  { jp: "困難",     reading: "こんなん",   ko: "곤란/어려움",  tag: "difficulty" },
  { jp: "危機",     reading: "きき",       ko: "위기",         tag: "crisis" },
  { jp: "弱点",     reading: "じゃくてん", ko: "약점",         tag: "weakness" },
  { jp: "経歴",     reading: "けいれき",   ko: "경력",         tag: "career" },
  { jp: "作品",     reading: "さくひん",   ko: "작품",         tag: "art" },
  { jp: "工芸",     reading: "こうげい",   ko: "공예",         tag: "craft" },
  { jp: "知識",     reading: "ちしき",     ko: "지식",         tag: "knowledge" },
  { jp: "技術力",   reading: "ぎじゅつりょく", ko: "기술력",   tag: "technique" },
  { jp: "資材",     reading: "しざい",     ko: "자재",         tag: "material" },
  { jp: "候補者",   reading: "こうほしゃ", ko: "후보자",       tag: "candidate" },
  { jp: "支店",     reading: "してん",     ko: "지점",         tag: "branch" },
  { jp: "チーム",   reading: "ちーむ",     ko: "팀",           tag: "team" },
  { jp: "プロジェクト", reading: "ぷろじぇくと", ko: "프로젝트", tag: "project" },
  { jp: "企画",     reading: "きかく",     ko: "기획",         tag: "proposal" },
  { jp: "データ",   reading: "でーた",     ko: "데이터",       tag: "data" },
  { jp: "情報",     reading: "じょうほう", ko: "정보",         tag: "info" },
  { jp: "日程",     reading: "にってい",   ko: "일정",         tag: "schedule" },
  { jp: "結果",     reading: "けっか",     ko: "결과",         tag: "result" },
  { jp: "試験",     reading: "しけん",     ko: "시험",         tag: "exam" },
  { jp: "旅行",     reading: "りょこう",   ko: "여행",         tag: "trip" },
  { jp: "イベント", reading: "いべんと",   ko: "이벤트",       tag: "event" },
  { jp: "会議",     reading: "かいぎ",     ko: "회의",         tag: "meeting" },
  { jp: "パーティー", reading: "ぱーてぃー", ko: "파티",       tag: "party" },
  { jp: "レストラン", reading: "れすとらん", ko: "레스토랑",   tag: "restaurant" },
  { jp: "ホテル",   reading: "ほてる",     ko: "호텔",         tag: "hotel" },
  { jp: "切符",     reading: "きっぷ",     ko: "티켓",         tag: "ticket" },
  { jp: "料理",     reading: "りょうり",   ko: "요리",         tag: "dish" },
  { jp: "皿",       reading: "さら",       ko: "접시",         tag: "dish" },
  { jp: "花",       reading: "はな",       ko: "꽃",           tag: "flower" },
  { jp: "プレゼント", reading: "ぷれぜんと", ko: "선물",       tag: "present" },
  { jp: "切手",     reading: "きって",     ko: "우표",         tag: "stamp" },
  { jp: "硬貨",     reading: "こうか",     ko: "동전",         tag: "coin" },
  { jp: "歴史",     reading: "れきし",     ko: "역사",         tag: "history" },
  { jp: "将来",     reading: "しょうらい", ko: "장래",         tag: "future" },
  { jp: "人生",     reading: "じんせい",   ko: "인생",         tag: "life" },
  { jp: "平和",     reading: "へいわ",     ko: "평화",         tag: "peace" },
  { jp: "品質",     reading: "ひんしつ",   ko: "품질",         tag: "quality" },
  { jp: "信頼",     reading: "しんらい",   ko: "신뢰",         tag: "trust" },
  { jp: "賞",       reading: "しょう",     ko: "상",           tag: "prize" },
  { jp: "免許",     reading: "めんきょ",   ko: "면허",         tag: "license" },
  { jp: "サービス", reading: "さーびす",   ko: "서비스",       tag: "service" },
  { jp: "システム", reading: "しすてむ",   ko: "시스템",       tag: "system" },
  { jp: "ソフトウェア", reading: "そふとうぇあ", ko: "소프트웨어", tag: "software" },
  { jp: "建物",     reading: "たてもの",   ko: "건물",         tag: "building" },
  { jp: "道路",     reading: "どうろ",     ko: "도로",         tag: "road" },
  { jp: "橋",       reading: "はし",       ko: "다리",         tag: "bridge" },
  { jp: "土地",     reading: "とち",       ko: "토지",         tag: "land" },
  { jp: "機械",     reading: "きかい",     ko: "기계",         tag: "machine" },
  { jp: "自動車",   reading: "じどうしゃ", ko: "승용차",       tag: "car" },
  { jp: "番組",     reading: "ばんぐみ",   ko: "프로그램",     tag: "program" },
  { jp: "店",       reading: "みせ",       ko: "가게",         tag: "shop" },
  { jp: "客",       reading: "きゃく",     ko: "손님",         tag: "guest" },
  { jp: "新年",     reading: "しんねん",   ko: "새해",         tag: "newyear" },
  { jp: "誕生日",   reading: "たんじょうび", ko: "생일",       tag: "birthday" },
  { jp: "仕事場",   reading: "しごとば",   ko: "직장",         tag: "job" },
  { jp: "言葉",     reading: "ことば",     ko: "말/언어",      tag: "word" },
  { jp: "名前",     reading: "なまえ",     ko: "이름",         tag: "name" },
  { jp: "メモ",     reading: "めも",       ko: "메모",         tag: "note" },
  { jp: "紙",       reading: "かみ",       ko: "종이",         tag: "paper" },
  { jp: "缶",       reading: "かん",       ko: "캔",           tag: "can" },
  { jp: "箱",       reading: "はこ",       ko: "상자",         tag: "box" },
  { jp: "体",       reading: "からだ",     ko: "몸",           tag: "body" },
  { jp: "傘",       reading: "かさ",       ko: "우산",         tag: "umbrella" },
  { jp: "物",       reading: "もの",       ko: "것/물건",      tag: "thing" },
  { jp: "間違い",   reading: "まちがい",   ko: "실수",         tag: "mistake" },
  { jp: "悩み",     reading: "なやみ",     ko: "고민",         tag: "trouble" },
  { jp: "手続き",   reading: "てつづき",   ko: "절차/서류처리", tag: "paperwork" },
  { jp: "技能",     reading: "ぎのう",     ko: "기능/스킬",    tag: "skill" }
];
