// JLPT N3 단어 — { jp, reading, ko, type? }
// type: "i" = い형용사 / "na" = な형용사 / 생략 = 명사·동사·부사(자동 분류)
const N3_WORDS = [

  // ── 명사 (80) ──
  { jp: "社会",     reading: "しゃかい",   ko: "사회" },
  { jp: "経済",     reading: "けいざい",   ko: "경제" },
  { jp: "政治",     reading: "せいじ",     ko: "정치" },
  { jp: "文化",     reading: "ぶんか",     ko: "문화" },
  { jp: "歴史",     reading: "れきし",     ko: "역사" },
  { jp: "科学",     reading: "かがく",     ko: "과학" },
  { jp: "技術",     reading: "ぎじゅつ",   ko: "기술" },
  { jp: "情報",     reading: "じょうほう", ko: "정보" },
  { jp: "環境",     reading: "かんきょう", ko: "환경" },
  { jp: "自然",     reading: "しぜん",     ko: "자연" },
  { jp: "資源",     reading: "しげん",     ko: "자원" },
  { jp: "エネルギー", reading: "えねるぎー", ko: "에너지" },
  { jp: "原子力",   reading: "げんしりょく", ko: "원자력" },
  { jp: "災害",     reading: "さいがい",   ko: "재해" },
  { jp: "地震",     reading: "じしん",     ko: "지진" },
  { jp: "台風",     reading: "たいふう",   ko: "태풍" },
  { jp: "洪水",     reading: "こうずい",   ko: "홍수" },
  { jp: "火事",     reading: "かじ",       ko: "화재" },
  { jp: "事故",     reading: "じこ",       ko: "사고" },
  { jp: "被害",     reading: "ひがい",     ko: "피해" },
  { jp: "救助",     reading: "きゅうじょ", ko: "구조/구제" },
  { jp: "法律",     reading: "ほうりつ",   ko: "법률" },
  { jp: "規則",     reading: "きそく",     ko: "규칙" },
  { jp: "条約",     reading: "じょうやく", ko: "조약" },
  { jp: "契約",     reading: "けいやく",   ko: "계약" },
  { jp: "義務",     reading: "ぎむ",       ko: "의무" },
  { jp: "権利",     reading: "けんり",     ko: "권리" },
  { jp: "責任",     reading: "せきにん",   ko: "책임" },
  { jp: "税金",     reading: "ぜいきん",   ko: "세금" },
  { jp: "料金",     reading: "りょうきん", ko: "요금" },
  { jp: "費用",     reading: "ひよう",     ko: "비용" },
  { jp: "予算",     reading: "よさん",     ko: "예산" },
  { jp: "収入",     reading: "しゅうにゅう", ko: "수입" },
  { jp: "支出",     reading: "ししゅつ",   ko: "지출" },
  { jp: "利益",     reading: "りえき",     ko: "이익" },
  { jp: "損失",     reading: "そんしつ",   ko: "손실" },
  { jp: "株",       reading: "かぶ",       ko: "주식" },
  { jp: "市場",     reading: "しじょう",   ko: "시장" },
  { jp: "景気",     reading: "けいき",     ko: "경기" },
  { jp: "貿易",     reading: "ぼうえき",   ko: "무역" },
  { jp: "輸出",     reading: "ゆしゅつ",   ko: "수출" },
  { jp: "輸入",     reading: "ゆにゅう",   ko: "수입(수입품)" },
  { jp: "産業",     reading: "さんぎょう", ko: "산업" },
  { jp: "農業",     reading: "のうぎょう", ko: "농업" },
  { jp: "工業",     reading: "こうぎょう", ko: "공업" },
  { jp: "商業",     reading: "しょうぎょう", ko: "상업" },
  { jp: "製造",     reading: "せいぞう",   ko: "제조" },
  { jp: "製品",     reading: "せいひん",   ko: "제품" },
  { jp: "品質",     reading: "ひんしつ",   ko: "품질" },
  { jp: "設備",     reading: "せつび",     ko: "설비" },
  { jp: "機械",     reading: "きかい",     ko: "기계" },
  { jp: "工場",     reading: "こうじょう", ko: "공장" },
  { jp: "建築",     reading: "けんちく",   ko: "건축" },
  { jp: "建物",     reading: "たてもの",   ko: "건물" },
  { jp: "土地",     reading: "とち",       ko: "토지" },
  { jp: "不動産",   reading: "ふどうさん", ko: "부동산" },
  { jp: "家賃",     reading: "やちん",     ko: "집세" },
  { jp: "引っ越し", reading: "ひっこし",   ko: "이사" },
  { jp: "地域",     reading: "ちいき",     ko: "지역" },
  { jp: "都市",     reading: "とし",       ko: "도시" },
  { jp: "農村",     reading: "のうそん",   ko: "농촌" },
  { jp: "人口",     reading: "じんこう",   ko: "인구" },
  { jp: "住民",     reading: "じゅうみん", ko: "주민" },
  { jp: "国民",     reading: "こくみん",   ko: "국민" },
  { jp: "市民",     reading: "しみん",     ko: "시민" },
  { jp: "投票",     reading: "とうひょう", ko: "투표" },
  { jp: "選挙",     reading: "せんきょ",   ko: "선거" },
  { jp: "政府",     reading: "せいふ",     ko: "정부" },
  { jp: "国際",     reading: "こくさい",   ko: "국제" },
  { jp: "外交",     reading: "がいこう",   ko: "외교" },
  { jp: "平和",     reading: "へいわ",     ko: "평화" },
  { jp: "戦争",     reading: "せんそう",   ko: "전쟁" },
  { jp: "軍隊",     reading: "ぐんたい",   ko: "군대" },
  { jp: "武器",     reading: "ぶき",       ko: "무기" },
  { jp: "兵器",     reading: "へいき",     ko: "병기" },
  { jp: "核",       reading: "かく",       ko: "핵" },
  { jp: "平和条約", reading: "へいわじょうやく", ko: "평화조약" },
  { jp: "人類",     reading: "じんるい",   ko: "인류" },

  // ── 동사 (60) ──
  { jp: "減る",       reading: "へる",       ko: "줄다" },
  { jp: "増える",     reading: "ふえる",     ko: "늘다" },
  { jp: "上がる",     reading: "あがる",     ko: "오르다" },
  { jp: "下がる",     reading: "さがる",     ko: "내려가다" },
  { jp: "上がれる",   reading: "あがられる", ko: "올라갈 수 있다" },
  { jp: "下げる",     reading: "さげる",     ko: "낮추다" },
  { jp: "比較する",   reading: "ひかくする", ko: "비교하다" },
  { jp: "調査する",   reading: "ちょうさする", ko: "조사하다" },
  { jp: "研究する",   reading: "けんきゅうする", ko: "연구하다" },
  { jp: "開発する",   reading: "かいはつする", ko: "개발하다" },
  { jp: "改善する",   reading: "かいぜんする", ko: "개선하다" },
  { jp: "改良する",   reading: "かいりょうする", ko: "개량하다" },
  { jp: "改正する",   reading: "かいせいする", ko: "개정하다" },
  { jp: "改訂する",   reading: "かいていする", ko: "개정하다" },
{ jp: "修正する", reading: "しゅうせいする", ko: "수정하다" },
  { jp: "処理する",   reading: "しょりする", ko: "처리하다" },
  { jp: "管理する",   reading: "かんりする", ko: "관리하다" },
  { jp: "経営する",   reading: "けいえいする", ko: "경영하다" },
  { jp: "運営する",   reading: "うんえいする", ko: "운영하다" },
  { jp: "指導する",   reading: "しどうする", ko: "지도하다" },
  { jp: "教育する",   reading: "きょういくする", ko: "교육하다" },
  { jp: "訓練する",   reading: "くんれんする", ko: "훈련하다" },
  { jp: "養成する",   reading: "ようせいする", ko: "양성하다" },
  { jp: "育てる",     reading: "そだてる",   ko: "기르다" },
  { jp: "守る",       reading: "まもる",     ko: "지키다" },
  { jp: "保護する",   reading: "ほごする",   ko: "보호하다" },
  { jp: "救助する",   reading: "きゅうじょする", ko: "구조하다" },
  { jp: "救う",       reading: "すくう",     ko: "구하다" },
  { jp: "助かる",     reading: "たすかる",   ko: "도움을 받다/구조되다" },
  { jp: "助ける",     reading: "たすける",   ko: "돕다" },
  { jp: "支える",     reading: "ささえる",   ko: "지지하다/떠받치다" },
  { jp: "支える",     reading: "つかえる",   ko: "가로막다" },
  { jp: "妨げる",     reading: "さまたげる", ko: "방해하다" },
  { jp: "邪魔する",   reading: "じゃまする", ko: "방해하다" },
  { jp: "促進する",   reading: "そくしんする", ko: "촉진하다" },
  { jp: "推進する",   reading: "すいしんする", ko: "추진하다" },
  { jp: "推薦する",   reading: "すいせんする", ko: "추천하다" },
  { jp: "支持する",   reading: "しじする",   ko: "지지하다" },
  { jp: "賛成する",   reading: "さんせいする", ko: "찬성하다" },
  { jp: "反対する",   reading: "はんたいする", ko: "반대하다" },
  { jp: "抗議する",   reading: "こうぎする", ko: "항의하다" },
  { jp: "抗議",       reading: "こうぎ",     ko: "항의" },
  { jp: "主張する",   reading: "しゅちょうする", ko: "주장하다" },
  { jp: "要求する",   reading: "ようきゅうする", ko: "요구하다" },
  { jp: "請求する",   reading: "せいきゅうする", ko: "청구하다" },
  { jp: "申請する",   reading: "しんせいする", ko: "신청하다" },
  { jp: "届ける",     reading: "とどける",   ko: "신고하다/전하다" },
  { jp: "届く",       reading: "とどく",     ko: "도착하다/닿다" },
  { jp: "提出する",   reading: "ていしゅつする", ko: "제출하다" },
  { jp: "提供する",   reading: "ていきょうする", ko: "제공하다" },
  { jp: "供給する",   reading: "きょうきゅうする", ko: "공급하다" },
  { jp: "需要",       reading: "じゅうよう", ko: "수요" },
  { jp: "消費する",   reading: "しょうひする", ko: "소비하다" },
  { jp: "節約する",   reading: "せつやくする", ko: "절약하다" },
  { jp: "投資する",   reading: "とうしする", ko: "투자하다" },
  { jp: "貯金する",   reading: "ちょきんする", ko: "저금하다" },
  { jp: "交換する",   reading: "こうかんする", ko: "교환하다" },
  { jp: "輸送する",   reading: "ゆそうする", ko: "수송하다" },
  { jp: "配達する",   reading: "はいたつする", ko: "배달하다" },
  { jp: "出荷する",   reading: "しゅっかする", ko: "출하하다" },

  // ── い형용사 (15) ──
  { jp: "重い",     reading: "おもい",     ko: "무겁다",     type: "i" },
  { jp: "軽い",     reading: "かるい",     ko: "가볍다",     type: "i" },
  { jp: "硬い",     reading: "かたい",     ko: "딱딱하다",   type: "i" },
  { jp: "柔らかい", reading: "やわらかい", ko: "부드럽다",   type: "i" },
  { jp: "細い",     reading: "ほそい",     ko: "가늘다",     type: "i" },
  { jp: "太い",     reading: "ふとい",     ko: "굵다",       type: "i" },
  { jp: "厚い",     reading: "あつい",     ko: "두껍다",     type: "i" },
  { jp: "薄い",     reading: "うすい",     ko: "얇다",       type: "i" },
  { jp: "深い",     reading: "ふかい",     ko: "깊다",       type: "i" },
  { jp: "浅い",     reading: "あさい",     ko: "얕다",       type: "i" },
  { jp: "鋭い",     reading: "するどい",   ko: "날카롭다",   type: "i" },
  { jp: "鈍い",     reading: "にぶい",     ko: "둔하다",     type: "i" },
  { jp: "堅い",     reading: "かたい",     ko: "굳다/딱딱하다", type: "i" },
  { jp: "湿っぽい", reading: "しつっぽい", ko: "습하다/눅눅하다", type: "i" },
  { jp: "乾いた",   reading: "かわいた",   ko: "마른",       type: "i" },

  // ── な형용사 (15) ──
  { jp: "豊富",     reading: "ほうふ",     ko: "풍부하다",   type: "na" },
  { jp: "複雑",     reading: "ふくざつ",   ko: "복잡하다",   type: "na" },
  { jp: "簡単",     reading: "かんたん",   ko: "간단하다",   type: "na" },
  { jp: "正常",     reading: "せいじょう", ko: "정상이다",   type: "na" },
  { jp: "異常",     reading: "いじょう",   ko: "이상하다",   type: "na" },
  { jp: "普通",     reading: "ふつう",     ko: "보통이다",   type: "na" },
  { jp: "特別",     reading: "とくべつ",   ko: "특별하다",   type: "na" },
  { jp: "明確",     reading: "めいかく",   ko: "명확하다",   type: "na" },
  { jp: "曖昧",     reading: "あいまい",   ko: "애매하다",   type: "na" },
  { jp: "確実",     reading: "かくじつ",   ko: "확실하다",   type: "na" },
  { jp: "安全",     reading: "あんぜん",   ko: "안전하다",   type: "na" },
  { jp: "危険",     reading: "きけん",     ko: "위험하다",   type: "na" },
  { jp: "順調",     reading: "じゅんちょう", ko: "순조롭다", type: "na" },
  { jp: "悪化",     reading: "あっか",     ko: "악화(되다)", type: "na" },
  { jp: "円滑",     reading: "えんかつ",   ko: "원활하다",   type: "na" },

  // ── 부사 (30) ──
  { jp: "徐々に",     ko: "서서히" },
  { jp: "次第に",     ko: "점차" },
  { jp: "急に",       ko: "갑자기" },
  { jp: "突然",       ko: "돌연" },
  { jp: "ますます",   ko: "더욱더" },
  { jp: "ますます増える", ko: "점점 늘어나다" },
  { jp: "ほぼ",       ko: "거의" },
  { jp: "およそ",     ko: "약/대체로" },
  { jp: "すべて",     ko: "모두" },
  { jp: "全く",       ko: "전혀" },
  { jp: "必ずしも",   ko: "반드시 ~은 아니다" },
  { jp: "確かに",     ko: "확실히" },
  { jp: "たしかに",   ko: "분명히" },
  { jp: "おそらく",   ko: "아마도" },
  { jp: "どうやら",   ko: "어찌 됐든/어떻게든" },
  { jp: "けっこう",   ko: "꽤" },
  { jp: "ずいぶん",   ko: "제법" },
  { jp: "かなり",     ko: "상당히" },
  { jp: "ひどく",     ko: "몹시" },
  { jp: "非常に",     ko: "매우" },
  { jp: "たいへん",   ko: "대단히" },
  { jp: "一層",       ko: "한층 더" },
  { jp: "依然として", ko: "여전히" },
  { jp: "すでに",     ko: "이미" },
  { jp: "ちょうど",   ko: "바로/딱" },
  { jp: "たまたま",   ko: "우연히" },
  { jp: "偶然",       ko: "우연히" },
  { jp: "意図的に",   ko: "의도적으로" },
  { jp: "徐行して",   ko: "서행하여" },
  { jp: "順番に",     ko: "차례로" }
];
