// JLPT N1 단어 — { jp, reading, ko, type? }
// type: "i" = い형용사 / "na" = な형용사 / 생략 = 명사·동사·부사(자동 분류)
const N1_WORDS = [

  // ── 명사 (1/2) ──
  { jp: "潜在",       reading: "せんざい",     ko: "잠재" },
  { jp: "顕在",       reading: "けんざい",     ko: "현재" },
  { jp: "萌芽",       reading: "ほうが",       ko: "싹/새 단서" },
  { jp: "端緒",       reading: "たんしょ",     ko: "실마리" },
  { jp: "嚆矢",       reading: "こうし",       ko: "시초/신호탄" },
  { jp: "濫觴",       reading: "らんしょう",   ko: "발단/기원" },
  { jp: "淵源",       reading: "えんげん",     ko: "근원" },
  { jp: "淵叢",       reading: "えんそう",     ko: "깊은 소굴" },
  { jp: "薮蛇",       reading: "やぶへび",     ko: "뱀다덤" },
  { jp: "画蛇添足",   reading: "がだてんそく", ko: "남 짓기" },
  { jp: "提示",       reading: "ていじ",       ko: "제시" },
  { jp: "啓示",       reading: "けいじ",       ko: "계시" },
  { jp: "暗示",       reading: "あんじ",       ko: "암시" },
  { jp: "示唆",       reading: "しさ",         ko: "시사" },
  { jp: "含意",       reading: "がんい",       ko: "함의" },
  { jp: "内包",       reading: "ないほう",     ko: "내포" },
  { jp: "外延",       reading: "がいえん",     ko: "외연" },
  { jp: "相貌",       reading: "そうぼう",     ko: "상모/얼굴생김새" },
  { jp: "風貌",       reading: "ふうぼう",     ko: "풍모" },
  { jp: "様相",       reading: "ようそう",     ko: "양상" },
  { jp: "形態",       reading: "けいたい",     ko: "형태" },
  { jp: "態様",       reading: "たいよう",     ko: "형국" },
  { jp: "趣旨",       reading: "しゅし",       ko: "취지" },
  { jp: "旨趣",       reading: "ししゅ",       ko: "취지" },
  { jp: "要諦",       reading: "ようてい",     ko: "요체" },
  { jp: "肯綮",       reading: "こうけい",     ko: "요점" },
  { jp: "急所",       reading: "きゅうしょ",   ko: "급소" },
  { jp: "咽喉",       reading: "いんこう",     ko: "목구멍/요긴한 곳" },
  { jp: "咽喉部",     reading: "いんこうぶ",   ko: "인두부" },
  { jp: "臨界",       reading: "りんかい",     ko: "임계" },
  { jp: "閾値",       reading: "しきいち",     ko: "임계값" },
  { jp: "分水嶺",     reading: "ぶんすいれい", ko: "분수령" },
  { jp: "岐路",       reading: "きろ",         ko: "갈림길" },
  { jp: "歧路",       reading: "きろ",         ko: "갈림길" },
  { jp: "十字路",     reading: "じゅうじろ",   ko: "십자로" },
  { jp: "窄まり",     reading: "すぼまり",     ko: "좁아진 부분" },
  { jp: "隘路",       reading: "あいろ",       ko: "요로/난관" },
  { jp: "難関",       reading: "なんかん",     ko: "난관" },
  { jp: "関門",       reading: "かんもん",     ko: "관문" },
  { jp: "門戸",       reading: "もんこ",       ko: "문호" },
  { jp: "窮余",       reading: "きゅうよ",     ko: "궁여" },
  { jp: "窮地",       reading: "きゅうち",     ko: "궁지" },
  { jp: "危地",       reading: "きち",         ko: "위기" },
  { jp: "瀬戸際",     reading: "せとぎわ",     ko: "중요한 고비" },
  { jp: "踏ん切り",   reading: "ふんぎり",     ko: "결심" },
  { jp: "決意",       reading: "けつい",       ko: "결의" },
  { jp: "覚悟",       reading: "かくご",       ko: "각오" },
  { jp: "腹括り",     reading: "はらぐくり",   ko: "결의/각오" },
  { jp: "胆力",       reading: "たんりょく",   ko: "용기/담력" },
  { jp: "度胸",       reading: "どきょう",     ko: "담력" },
  { jp: "肝玉",       reading: "きもだま",     ko: "담력" },
  { jp: "肥やし",     reading: "こやし",       ko: "거름/자양분" },
  { jp: "糧",         reading: "かて",         ko: "식량/양식" },
  { jp: "滋養",       reading: "じよう",       ko: "자양" },
  { jp: "養分",       reading: "ようぶん",     ko: "양분" },
  { jp: "栄養",       reading: "えいよう",     ko: "영양" },
  { jp: "肥沃",       reading: "ひよく",       ko: "비옥" },
  { jp: "痩せ",       reading: "やせ",         ko: "마름" },
  { jp: "礎",         reading: "いしずえ",     ko: "토대/기초" },
  { jp: "基石",       reading: "きせき",       ko: "기초/첫걸음" },
  { jp: "土台",       reading: "どだい",       ko: "토대" },
  { jp: "下地",       reading: "したじ",       ko: "밑바탕" },
  { jp: "下地",       reading: "したじ",       ko: "밑바탕" },
  { jp: "素地",       reading: "そじ",         ko: "소질/밑바탕" },
  { jp: "素質",       reading: "そしつ",       ko: "소질" },
  { jp: "資質",       reading: "ししつ",       ko: "자질" },
  { jp: "資質",       reading: "ししつ",       ko: "자질" },
  { jp: "資料",       reading: "しりょう",     ko: "자료" },
  { jp: "史料",       reading: "しりょう",     ko: "사료" },
  { jp: "資源",       reading: "しげん",       ko: "자원" },
  { jp: "鉱脈",       reading: "こうみゃく",   ko: "광맥" },
  { jp: "鉱床",       reading: "こうしょう",   ko: "광상" },
  { jp: "地層",       reading: "ちそう",       ko: "지층" },
  { jp: "層",         reading: "そう",         ko: "층" },
  { jp: "層序",       reading: "そうじょ",     ko: "층서" },
  { jp: "断層",       reading: "だんそう",     ko: "단층" },
  { jp: "褶曲",       reading: "しゅうきょく", ko: "습곡" },
  { jp: "隆起",       reading: "りゅうき",     ko: "융기" },
  { jp: "沈降",       reading: "ちんこう",     ko: "침강" },
  { jp: "侵食",       reading: "しんしょく",   ko: "침식" },
  { jp: "風化",       reading: "ふうか",       ko: "풍화" },
  { jp: "変質",       reading: "へんしつ",     ko: "변질" },
  { jp: "変容",       reading: "へんよう",     ko: "변모" },
  { jp: "変貌",       reading: "へんぼう",     ko: "변모" },
  { jp: "激変",       reading: "げきへん",     ko: "격변" },
  { jp: "急変",       reading: "きゅうへん",   ko: "급변" },
  { jp: "転換",       reading: "てんかん",     ko: "전환" },
  { jp: "転回",       reading: "てんかい",     ko: "전회" },
  { jp: "回帰",       reading: "かいき",       ko: "회귀" },
  { jp: "還元",       reading: "かんげん",     ko: "환원" },
  { jp: "還流",       reading: "かんりゅう",   ko: "환류" },
  { jp: "循環",       reading: "じゅんかん",   ko: "순환" },
  { jp: "周流",       reading: "しゅうりゅう", ko: "주류/순환" },
  { jp: "潮流",       reading: "ちょうりゅう", ko: "조류/흐름" },
  { jp: "風潮",       reading: "ふうちょう",   ko: "풍조" },
  { jp: "風土",       reading: "ふうど",       ko: "풍토" },
  { jp: "気風",       reading: "きふう",       ko: "기풍" },
  { jp: "気質",       reading: "きしつ",       ko: "기질" },
  { jp: "気性",       reading: "きしょう",     ko: "기질" },
  { jp: "性根",       reading: "しょうね",     ko: "근성/본성" },
  { jp: "根性",       reading: "こんじょう",   ko: "근성" },
  { jp: "性分",       reading: "しょうぶん",   ko: "성품" },
  { jp: "脾腹",       reading: "ひばら",       ko: "성미" },
  { jp: "癖",         reading: "くせ",         ko: "버릇" },
  { jp: "習癖",       reading: "しゅうへき",   ko: "습관/버릇" },
  { jp: "嗜癖",       reading: "しへき",       ko: "중독성 취미" },
  { jp: "嗜好",       reading: "しこう",       ko: "기호/취미" },
  { jp: "嗜好品",     reading: "しこうひん",   ko: "기호품" },
  { jp: "趣向",       reading: "しゅこう",     ko: "취향/고안" },
  { jp: "趣向",       reading: "しゅこう",     ko: "취향/고안" },
  { jp: "意匠",       reading: "いしょう",     ko: "의장/디자인" },
  { jp: "意図",       reading: "いと",         ko: "의도" },
  { jp: "企図",       reading: "きと",         ko: "기도" },
  { jp: "企て",       reading: "くわだて",     ko: "계획" },
  { jp: "目論見",     reading: "もうろみ",     ko: "계획/목적" },
  { jp: "算段",       reading: "さんだん",     ko: "꾀/계산" },
  { jp: "画策",       reading: "かくさく",     ko: "공모" },
  { jp: "策謀",       reading: "さくぼう",     ko: "책모" },
  { jp: "陰謀",       reading: "いんぼう",     ko: "음모" },
  { jp: "野望",       reading: "やぼう",       ko: "야망" },
  { jp: "野心",       reading: "やしん",       ko: "야심" },
  { jp: "大志",       reading: "たいし",       ko: "큰 포부" },
  { jp: "抱負",       reading: "ほうふ",       ko: "포부" },
  { jp: "志",         reading: "こころざし",   ko: "뜻" },
  { jp: "念願",       reading: "ねんがん",     ko: "소원" },
  { jp: "宿願",       reading: "しゅくがん",   ko: "오랜 소원" },
  { jp: "夙願",       reading: "しゅくがん",   ko: "일찍부터 품은 소원" },
  { jp: "悲願",       reading: "ひがん",       ko: "간절한 소원" },
  { jp: "祈願",       reading: "きがん",       ko: "기원" },
  { jp: "念頭",       reading: "ねんとう",     ko: "머릿속" },
  { jp: "胸中",       reading: "きょうちゅう", ko: "속마음" },
  { jp: "心底",       reading: "しんそこ",     ko: "마음 깊은 곳" },
  { jp: "肺腑",       reading: "はいふ",       ko: "폐부(마음 깊은 곳)" },
  { jp: "魂",         reading: "たましい",     ko: "혼" },
  { jp: "精髄",       reading: "せいずい",     ko: "정수" },
  { jp: "真髄",       reading: "しんずい",     ko: "정수/진수" },
  { jp: "真骨頂",     reading: "しんこっちょう", ko: "진가가 드러나는 것" },
  { jp: "本懐",       reading: "ほんかい",     ko: "본래의 소망" },
  { jp: "本領",       reading: "ほんりょう",   ko: "본령" },
  { jp: "面目",       reading: "めんもく",     ko: "체면" },
  { jp: "体面",       reading: "たいめん",     ko: "체면" },
  { jp: "面子",       reading: "めんつ",       ko: "체면" },

  // ── 동사 (60) ──
  { jp: "覆う",       reading: "おおう",       ko: "덮다/뒤덮다" },
  { jp: "被る",       reading: "かぶる",       ko: "쓰다/입다(피해를)" },
  { jp: "蒙る",       reading: "こうむる",     ko: "입다(피해)/받다" },
  { jp: "被せる",     reading: "かぶせる",     ko: "덮어 씌우다" },
  { jp: "着せる",     reading: "きせる",       ko: "입혀 주다/씌우다" },
{ jp: "纏う",     reading: "まとう",     ko: "두르다/걸치다" },
  { jp: "帯びる",     reading: "おびる",       ko: "지니다/띠다" },
  { jp: "宿す",       reading: "やどす",       ko: "지니다/담다" },
  { jp: "秘める",     reading: "ひめる",       ko: "숨기다/간직하다" },
  { jp: "抱き込む",   reading: "だきこむ",     ko: "끌어들이다" },
  { jp: "絡める",     reading: "からめる",     ko: "얽다/관련시키다" },
  { jp: "絡む",       reading: "からむ",       ko: "얽히다/관련되다" },
  { jp: "絡み合う",   reading: "からみあう",   ko: "서로 얽히다" },
  { jp: "交える",     reading: "まじえる",     ko: "섞다/가미하다" },
  { jp: "交わる",     reading: "まじわる",     ko: "어울리다/교차하다" },
  { jp: "交わす",     reading: "かわす",       ko: "주고받다" },
  { jp: "混ぜる",     reading: "まぜる",       ko: "섞다" },
  { jp: "混じる",     reading: "まじる",       ko: "섞이다" },
  { jp: "紛れる",     reading: "まぎれる",     ko: "혼동되다/잊다" },
  { jp: "紛らわす",   reading: "まぎらわす",   ko: "해소하다/전환시키다" },
  { jp: "潜む",       reading: "ひそむ",       ko: "숨다/잠재하다" },
  { jp: "潜る",       reading: "もぐる",       ko: "잠수하다/숨어들다" },
  { jp: "忍ぶ",       reading: "しのぶ",       ko: "숨다/그리워하다" },
  { jp: "隠れる",     reading: "かくれる",     ko: "숨다" },
  { jp: "隠す",       reading: "かくす",       ko: "숨기다" },
  { jp: "匿う",       reading: "かくまう",     ko: "숨겨 주다/보호하다" },
  { jp: "覆い隠す",   reading: "おおいかくす", ko: "덮어 숨기다" },
  { jp: "瞑る",       reading: "つむる",       ko: "눈을 감다" },
  { jp: "閉ざす",     reading: "とざす",       ko: "닫다/봉쇄하다" },
  { jp: "塞ぐ",       reading: "ふさぐ",       ko: "막다/울적하다" },
  { jp: "塞がる",     reading: "ふさがる",     ko: "막히다/차다" },
  { jp: "埋まる",     reading: "うまる",       ko: "메워지다/묻히다" },
  { jp: "埋める",     reading: "うめる",       ko: "메우다" },
  { jp: "埋没する",   reading: "まいぼつする", ko: "매몰되다" },
  { jp: "湮滅する",   reading: "いんめつする", ko: "멸실되다" },
  { jp: "消え去る",   reading: "きえさる",     ko: "사라지다" },
  { jp: "去る",       reading: "さる",         ko: "떠나다" },
  { jp: "立ち去る",   reading: "たちさる",     ko: "자리를 떠나다" },
  { jp: "見捨てる",   reading: "みすてる",     ko: "팔아치우다/외면하다" },
  { jp: "見放す",     reading: "みはなす",     ko: "체념하고 버리다" },
  { jp: "打ち捨てる", reading: "うちすてる",   ko: "버리다/방치하다" },
  { jp: "遺す",       reading: "のこす",       ko: "남기다" },
  { jp: "遺る",       reading: "のこる",       ko: "남다" },
  { jp: "残る",       reading: "のこる",       ko: "남다" },
  { jp: "残す",       reading: "のこす",       ko: "남기다" },
  { jp: "滅びる",     reading: "ほろびる",     ko: "멸망하다" },
  { jp: "滅ぼす",     reading: "ほろぼす",     ko: "멸망시키다" },
  { jp: "廃れる",     reading: "すたれる",     ko: "쇠퇴하다" },
  { jp: "廃する",     reading: "はいする",     ko: "폐지하다" },
  { jp: "衰える",     reading: "おとろえる",   ko: "쇠퇴하다/약해지다" },
  { jp: "靡く",       reading: "なびく",       ko: "나부끼다/휘어지다" },
  { jp: "靡かす",     reading: "なびかす",     ko: "나부끼게 하다" },
  { jp: "揺らぐ",     reading: "ゆらぐ",       ko: "흔들리다" },
  { jp: "揺らぐ",     reading: "ゆらぐ",       ko: "흔들리다/동요되다" },
  { jp: "動揺する",   reading: "どうようする", ko: "동요하다" },
  { jp: "揺さぶる",   reading: "ゆさぶる",     ko: "흔들다/동요시키다" },
  { jp: "煽る",       reading: "あおる",       ko: "부추기다/선동하다" },
  { jp: "駆り立てる", reading: "かりたてる",   ko: "몰아세우다" },

  // ── い형용사 (10) ──
  { jp: "惜しい",     reading: "おしい",       ko: "아깝다", type: "i" },
  { jp: "口惜しい",   reading: "くちおしい",   ko: "분하고 아쉽다", type: "i" },
  { jp: "心細い",     reading: "こころぼそい", ko: "마음이 허전하다", type: "i" },
  { jp: "望ましい",   reading: "のぞましい",   ko: "바람직하다", type: "i" },
  { jp: "騒がしい",   reading: "さわがしい",   ko: "소란스럽다", type: "i" },
  { jp: "煩い",       reading: "うるさい",     ko: "시끄럽다", type: "i" },
  { jp: "懐かしい",   reading: "なつかしい",   ko: "그립다", type: "i" },
  { jp: "生暖かい",   reading: "なまあたたかい", ko: "미지근하다", type: "i" },
  { jp: "生憎",       reading: "あいにく",     ko: "불행히도", type: "na" },
  { jp: "もったいない", reading: "もったいない", ko: "아깝다", type: "i" },

  // ── な형용사 (10) ──
  { jp: "莫大",       reading: "ばくだい",     ko: "막대하다", type: "na" },
  { jp: "多額",       reading: "たがく",       ko: "많은 액수", type: "na" },
  { jp: "僅少",       reading: "きんしょう",   ko: "극소량", type: "na" },
  { jp: "微々たる",   reading: "びびたる",     ko: "미미하다", type: "na" },
  { jp: "未熟",       reading: "みじゅく",     ko: "미숙하다", type: "na" },
  { jp: "円熟",       reading: "えんじゅく",   ko: "원숙", type: "na" },
  { jp: "熟達",       reading: "じゅくたつ",   ko: "숙달", type: "na" },
  { jp: "老獪",       reading: "ろうけつ",     ko: "노환하다", type: "na" },
  { jp: "狡猾",       reading: "こうかつ",     ko: "교활하다", type: "na" },
  { jp: "抜け目ない", reading: "ぬけめない",   ko: "구멍 없이 빈틈없다", type: "i" },

  // ── 부사 (20) ──
  { jp: "はなはだ",     ko: "지나치게/매우" },
  { jp: "いたく",       ko: "몹시" },
  { jp: "至って",       ko: "지극히" },
  { jp: "すこぶる",     ko: "몹시/대단히" },
  { jp: "やけに",       ko: "지나치게" },
  { jp: "やたらに",     ko: "함부로/지나치게" },
  { jp: "ひとえに",     ko: "오로지" },
  { jp: "もっぱら",     ko: "전적으로/오로지" },
  { jp: "いたずらに",   ko: "헛되이" },
  { jp: "いたずらに",   ko: "헛되이" },
  { jp: "やみくもに",   ko: "무턱대고" },
  { jp: "がむしゃらに", ko: "멋대로/무작정" },
  { jp: "しんみり",     ko: "조용히/감회에 젖어" },
  { jp: "しみじみ",     ko: "깊이 실감하며" },
  { jp: "つくづく",     ko: "새삼 깊이" },
  { jp: "かねがね",     ko: "전부터" },
  { jp: "かねてより",   ko: "미리부터/예전부터" },
  { jp: "あらかじめ",   ko: "미리" },
  { jp: "よほど",       ko: "꽤/아주" },
  { jp: "よほど",       ko: "꽤/차라리" }
];
