// JLPT N4 단어 — { jp, reading, ko, type? }
const N4_WORDS = [

  // ── 명사 (50) ──
  { jp: "世界",     reading: "せかい",     ko: "세계" },
  { jp: "地図",     reading: "ちず",       ko: "지도" },
  { jp: "新聞",     reading: "しんぶん",   ko: "신문" },
  { jp: "雑誌",     reading: "ざっし",     ko: "잡지" },
  { jp: "辞書",     reading: "じしょ",     ko: "사전" },
  { jp: "作文",     reading: "さくぶん",   ko: "작문" },
  { jp: "意味",     reading: "いみ",       ko: "의미" },
  { jp: "発音",     reading: "はつおん",   ko: "발음" },
  { jp: "漢字",     reading: "かんじ",     ko: "한자" },
  { jp: "文法",     reading: "ぶんぽう",   ko: "문법" },
  { jp: "感想",     reading: "かんそう",   ko: "감상" },
  { jp: "意見",     reading: "いけん",     ko: "의견" },
  { jp: "経験",     reading: "けいけん",   ko: "경험" },
  { jp: "遠慮",     reading: "えんりょ",   ko: "사양/겸양" },
  { jp: "都合",     reading: "つごう",     ko: "사정" },
  { jp: "用事",     reading: "ようじ",     ko: "볼일" },
  { jp: "予定",     reading: "よてい",     ko: "예정" },
  { jp: "都内",     reading: "とない",     ko: "도내" },
  { jp: "近所",     reading: "きんじょ",   ko: "근처/이웃" },
  { jp: "向こう",   reading: "むこう",     ko: "맞은편/저쪽" },
  { jp: "出入り口", reading: "でいりぐち", ko: "출입구" },
  { jp: "出入国",   reading: "しゅつにゅうこく", ko: "출입국" },
  { jp: "種類",     reading: "しゅるい",   ko: "종류" },
  { jp: "値段",     reading: "ねだん",     ko: "값" },
  { jp: "半分",     reading: "はんぶん",   ko: "절반" },
  { jp: "全部",     reading: "ぜんぶ",     ko: "전부" },
  { jp: "大部分",   reading: "だいぶぶん", ko: "대부분" },
  { jp: "千円",     reading: "せんえん",   ko: "천 엔" },
  { jp: "実",       reading: "み",         ko: "열매" },
  { jp: "枝",       reading: "えだ",       ko: "가지" },
  { jp: "森",       reading: "もり",       ko: "숲" },
  { jp: "原っぱ",   reading: "はらっぱ",   ko: "빈터" },
  { jp: "川原",     reading: "かわら",     ko: "강가 모래땅" },
  { jp: "庭園",     reading: "ていえん",   ko: "정원" },
  { jp: "通り",     reading: "とおり",     ko: "거리/대로" },
  { jp: "横",       reading: "よこ",       ko: "옆" },
  { jp: "縦",       reading: "たて",       ko: "세로" },
  { jp: "斜め",     reading: "ななめ",     ko: "비스듬히" },
  { jp: "角",       reading: "かど",       ko: "모서리/모퉁이" },
  { jp: "柱",       reading: "はしら",     ko: "기둥" },
  { jp: "床",       reading: "ゆか",       ko: "마루" },
  { jp: "天井",     reading: "てんじょう", ko: "천장" },
  { jp: "屋根",     reading: "やね",       ko: "지붕" },
  { jp: "壁",       reading: "かべ",       ko: "벽" },
  { jp: "階段",     reading: "かいだん",   ko: "계단" },
  { jp: "表",       reading: "おもて",     ko: "겉/앞면" },
  { jp: "裏",       reading: "うら",       ko: "뒷면" },
  { jp: "度",       reading: "ど",         ko: "도(각도/차수)" },
  { jp: "温度",     reading: "おんど",     ko: "온도" },
  { jp: "季節",     reading: "きせつ",     ko: "계절" },

  // ── 동사 (30) ──
  { jp: "上げる",     reading: "あげる",     ko: "올리다/들어주다" },
  { jp: "受ける",     reading: "うける",     ko: "받다" },
  { jp: "選ぶ",       reading: "えらぶ",     ko: "고르다" },
  { jp: "遅れる",     reading: "おくれる",   ko: "늦다" },
  { jp: "捕まえる",   reading: "つかまえる", ko: "잡다" },
  { jp: "似る",       reading: "にる",       ko: "닮다" },
  { jp: "脱ぐ",       reading: "ぬぐ",       ko: "벗다" },
  { jp: "負ける",     reading: "まける",     ko: "지다" },
  { jp: "間違える",   reading: "まちがえる", ko: "틀리다" },
  { jp: "殴る",       reading: "なぐる",     ko: "때리다" },
  { jp: "投げる",     reading: "なげる",     ko: "던지다" },
  { jp: "逃げる",     reading: "にげる",     ko: "도망치다" },
  { jp: "運ぶ",       reading: "はこぶ",     ko: "운반하다" },
  { jp: "掃く",       reading: "はく",       ko: "쓸다" },
  { jp: "運転する",   reading: "うんてんする", ko: "운전하다" },
  { jp: "発見する",   reading: "はっけんする", ko: "발견하다" },
  { jp: "翻訳する",   reading: "ほんやくする", ko: "번역하다" },
  { jp: "解釈する",   reading: "かいしゃくする", ko: "해석하다" },
  { jp: "確認する",   reading: "かくにんする", ko: "확인하다" },
  { jp: "練習する",   reading: "れんしゅうする", ko: "연습하다" },
  { jp: "説明する",   reading: "せつめいする", ko: "설명하다" },
  { jp: "予約する",   reading: "よやくする", ko: "예약하다" },
  { jp: "準備する",   reading: "じゅんびする", ko: "준비하다" },
  { jp: "洗濯する",   reading: "せんたくする", ko: "세탁하다" },
  { jp: "掃除する",   reading: "そうじする", ko: "청소하다" },
  { jp: "料理する",   reading: "りょうりする", ko: "요리하다" },
  { jp: "散髪する",   reading: "さんぱつする", ko: "이발하다" },
  { jp: "出迎える",   reading: "でむかえる", ko: "마중 나가다" },
  { jp: "送り返す",   reading: "おくりかえす", ko: "되돌려 보내다" },
  { jp: "振り返る",   reading: "ふりかえる", ko: "돌아보다" },

    // ── い형용사 (10) ──
  { jp: "憎い",     reading: "にくい",     ko: "미우다/원통하다", type: "i" },
  { jp: "醜い",     reading: "みにくい",   ko: "추하다",     type: "i" },
  { jp: "羨ましい", reading: "うらやましい", ko: "부럽다",   type: "i" },
  { jp: "恋しい",   reading: "こいしい",   ko: "그립다",     type: "i" },
  { jp: "煩わしい", reading: "わずらわしい", ko: "번거롭다", type: "i" },
  { jp: "勇ましい", reading: "いさましい", ko: "용맹하다",   type: "i" },
  { jp: "眩しい",   reading: "まぶしい",   ko: "눈부시다",   type: "i" },
  { jp: "嬉しい",   reading: "うれしい",   ko: "기쁘다",     type: "i" },
  { jp: "悲しい",   reading: "かなしい",   ko: "슬프다",     type: "i" },
  { jp: "痛い",     reading: "いたい",     ko: "아프다",     type: "i" },

  // ── な형용사 (9) ──
  { jp: "大変",     reading: "たいへん",   ko: "대단하다/힘들다", type: "na" },
  { jp: "妙",       reading: "みょう",     ko: "묘하다",     type: "na" },
  { jp: "滑稽",     reading: "こっけい",   ko: "우스꽝스럽다", type: "na" },
  { jp: "無邪気",   reading: "むじゃき",   ko: "천진하다",   type: "na" },
  { jp: "素敵",     reading: "すてき",     ko: "멋지다",     type: "na" },
  { jp: "魅力的",   reading: "みりょくてき", ko: "매력적이다", type: "na" },
  { jp: "個性的",   reading: "こせいてき", ko: "개성적이다", type: "na" },
  { jp: "積極的",   reading: "せっきょくてき", ko: "적극적이다", type: "na" },
  { jp: "派手",     reading: "はで",       ko: "화려하다",   type: "na" },

  // ── 부사 (15) ──
  { jp: "ますます",   ko: "더욱더" },
  { jp: "すっかり",   ko: "완전히" },
  { jp: "なかなか",   ko: "꽤/쉽게 ~않다" },
  { jp: "さっそく",   ko: "당장" },
  { jp: "わざわざ",   ko: "굳이" },
  { jp: "つい",       ko: "문득/~하고 만다" },
  { jp: "うっかり",   ko: "깜빡하고" },
  { jp: "ほんの少し", ko: "아주 조금" },
  { jp: "のんびり",   ko: "느긋하게" },
  { jp: "はっきり",   ko: "분명하게" },
  { jp: "うんと",     ko: "훨씬/많이" },
  { jp: "少々",       ko: "조금" },
  { jp: "相変わらず", ko: "여전히" },
  { jp: "まさに",     ko: "바로" },
  { jp: "どうしても", ko: "어떻게 해서든" }
];
